### ISSUE TITLE
documentation problems

### ISSUE THREAD

**Issue by mahrossi** [i-pi/i-pi#1]
Hi people - just to say that in the master branch of this "release version" the compilation of the manual here does not work at all, and in the v1 branch a lot of figures seem to be missing. Let me know if you want me to fix it. @i-pi/developers

**Comment by chemphys** [comment]
Hi, just a follow up, the documentation is still broken in the master branch. Is it possible to fix it? Thanks!

**Comment by OndrejMarsalek** [comment]
This is probably deprecated now, right? Can we close?
