### ISSUE TITLE
Initial velocities/momenta

### ISSUE THREAD

**Issue by kzinovjev** [i-pi/i-pi#10]
I am trying to propagate a deterministic RP trajectory both forward and backward in time, but there seems to be an issue with momenta initialization. The initial momenta are taken from an xyz file:

`<momenta mode="xyz">...</momenta>`

The values are obtained from a \<p\> tag in a RESTART file from previous dynamics. I noticed that even when the momenta are inversed, atoms still move in the same direction. Same is seen by writing out the momenta of one atom along the trajectory:
```
<properties stride='1' filename='vel'>
    [atom_p(atom=6;bead=0)]
</properties>
```
(By the way, the docs wrongly mention 'index' keyword instead of 'atom' on p.21)

For the first three steps I get the following for forward and backward trajectory respectively (dt=0.5fs):
```    
6.09068920e+00   5.35083150e+00  -1.44799839e+01
1.94354708e+03   5.71117205e+02   2.16511490e+03
2.09114928e+03   6.09894794e+02   2.34058299e+03
```
```
-6.09068920e+00  -5.35083150e+00   1.44799839e+01
1.93710946e+03   5.66526553e+02   2.18787261e+03
2.09615550e+03   6.16158483e+02   2.35486593e+03
```

It looks like the initial momenta are almost ignored. Also, the values for the second step are 2 orders of magnitude larger. Reducing the timestep to 0.01fs did not help:
```
6.09068920e+00   5.35083150e+00  -1.44799839e+01
2.29469152e+03   6.71378886e+02   2.56621115e+03
-3.85886876e+02  -1.18315972e+02  -4.30949729e+02
```
```
-6.09068920e+00  -5.35083150e+00   1.44799839e+01
2.29569119e+03   6.74427297e+02   2.58355172e+03
-3.73845606e+02  -1.04471922e+02  -4.21425754e+02
```

Also, the period of velocity fluctuations (measured in MD steps) is almost as short as with 0.5fs timestep, although one would expect it to become 50 times larger.
I also thought that I might have confused momenta/velocities. By changing `momenta` tag to `velocities` the system does move to opposite directions, but it explodes (not surprisingly, since the absolute values are 3 orders of magnitude larger).

Interestingly, the momenta of the centroid do look +- OK (`[atom_p(atom=6)]`, dt=0.01fs).
```
   -1.96622750e-02  -6.23456875e-01  -1.01544705e+01
    2.60683333e-02  -1.03155354e+00  -9.01691498e+00
    4.64858198e-02  -1.03329189e+00  -9.00537144e+00
```
```
    1.96622750e-02   6.23456875e-01   1.01544705e+01
    1.42735627e-02   1.02787397e+00   9.03966841e+00
    3.46887511e-02   1.02591221e+00   9.05119286e+00
```

So, what am I missing? Does i-pi do some extra magic with bead momenta?

I attach the input files necessary to reproduce the problem. cp2k-4.1 is used as the force driver. The test system is ethanol molecule in gas phase. For tests I use only 2 beads, but the same problem appears using more.

Thanks in advance!

[vodka.zip](https://github.com/i-pi/i-pi/files/1579168/vodka.zip)

**Comment by ceriottm** [comment]
Fixed long ago, just forgot to close the issue.

**Comment by ceriottm** [comment]
Dear @kzinovjev can you please try the development version of i-PI on https://github.com/cosmo-epfl/i-pi-dev and see if you can reproduce the bug? We are preparing a v2.0 release and I don't think this will be looked at before that is released so I'd rather see if the bug is still there and fix it in the new version.
