### ISSUE TITLE
fix atoms and fixcom

### ISSUE THREAD

**Issue by litman90** [i-pi/i-pi#101]
In the file ipi/inputs/motion/motion.py, at the end of the function "store"  there is a line
that aborts the simulation when  if (sc.fixcom is True) and (len(sc.fixatoms) > 0).

This forces to set fixcom to false manually in the input file. Is there any reason to not do it automatically? I can't imagine anyone, but maybe I am missing something.

**Comment by mahrossi** [comment]
I just saw this ~3 YEARS OLD (!!! ... !!!) comment now but no, can't see any reason, and in fact had a few of my calculations breaking because of that. Agree with making it automatic unless someone has a mind against it.

**Comment by mahrossi** [comment]
Addressed in #360
