### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by oschuett** [i-pi/i-pi#11]
Hi, I just wanted to let you know that I recently had to fix CP2K for a host which used IPv6 when a socket was opened with `AF_UNSPEC`: https://github.com/cp2k/cp2k/commit/cbaaf2de414d2fef738507a1302db829f9d4bb81

While most of i-Pi seems to use `AF_INET` there are still a few places where `AF_UNSPEC` is used:
https://github.com/i-pi/i-pi/search?q=AF_UNSPEC&unscoped_q=AF_UNSPEC

So, you might want to look into this IPv6 stuff at some point.

**Comment by ceriottm** [comment]
Thanks! So the i-PI interface in CP2K has been fixed? I didn't realize we were using AF_UNSPEC, I'll get @venkatkapil24 to have a quick look to make sure we are future-proof.

**Comment by venkatkapil24** [comment]
Thanks @oschuett. The driver code in i-pi now uses an IPv4 socket. Graduating to IPv6 to be fully future proof will be done later.
