### ISSUE TITLE
Tools in bin/ went from links to copies

### ISSUE THREAD

**Issue by ceriottm** [i-pi/i-pi#119]
Somewhere along the migration to py3 the tools, that used to be links to scripts in tools/pi, have turned into hard copies. This means we have lots of duplicate files, and the files in tools still live in python2 land. 
There should be some quick checking and then files from bin should be copied to tools, and the state of bin/ as a folder of links should be reinstated. Might also be a good time to get rid of tools that are not linked into bin, and haven't been touched in years.

**Comment by mahrossi** [comment]
Further, right now most scripts in tools are in py2 (this can be updated very soon and easily), but some scripts in bin have somehow been py3-ed. Unclear how exactly. Input is needed and full update of scripts to py3 is under way, soon.

**Comment by mahrossi** [comment]
Being addressed by PR #124
