### ISSUE TITLE
RE(PI)MD

### ISSUE THREAD

**Issue by chemphys** [i-pi/i-pi#12]
Hello! I have a question. I have been looking in the documentation and some open issues, but I haven't found the answer, so maybe you can either answer it or just point me to where it is.

Do you have implemented, or plan to implement, Replica-Exchange Path Integral Molecular dynamics? If is implemented, where are the test cases/examples? I want to hook my code to i-pi, but we are very interested in these kind of simulations, and not having them is a big perk. We would probably be happy with simple REMD for now, but knowing that there will be REPIMD will be helpful. 

If is not implemented, when do you plan to do it?

Thanks!

**Comment by mahrossi** [comment]
I can say that yes, it is implemented already and it features in an upcoming publication of i-PI v2.  It is part of the new "smotion" (super motion) class. Some examples are in examples/lammps/h2o-extreme-rem. @ceriottm can probably give more details.

**Comment by chemphys** [comment]
That is going to be perfect then. I am fighting with creating the driver for C++ using the libraries we have to get energy, for now. I might ask you for some help if I cannot make it myself. Thanks @mahrossi !

**Comment by ceriottm** [comment]
I can confirm that REMD works with whatever you throw at it, it has been definitely been tested with Trotter PIMD and constant pressure. Examples are in the examples folder.
