### ISSUE TITLE
C++ driver example

### ISSUE THREAD

**Issue by chemphys** [i-pi/i-pi#13]
Hi @mahrossi and @ceriottm ,
I was wondering if you have a C++ driver example for a generic force function. The fortran driver can help me translate it to c++, but i might miss something in there. 

I think that the only thing I need (a part from i-pi) is to have the sockets.c compiled and linked to my main program, and that will allow me to read/write data from/into i-pi. I tried a couple years ago to implement it, but at that point, since our software was not efficient, we decided to go with a small REPIMD routine we had, that did the job for a while. However, now we have a slightly powerful force calculation and I think is worth to have an MD driver that has been tested and working like this one.

I will probably keep bothering you guys in the upcoming week.
Thanks in advance! See you!

**Comment by ceriottm** [comment]
(1) LAMMPS is C++ and has an i-PI socket interface so you can use that as template
(2) you shouldn't use github issues to ask questions about features and how to use the code. The forum on ipi-code.org is there for that purpose.
