### ISSUE TITLE
PARATEMP FILE in REMD/REPIMD

### ISSUE THREAD

**Issue by litman90** [i-pi/i-pi#13]
The first column of the PARATEMP file which (I think) represents the step number. 
There is a shift of -1, i.e. when it says "0" it should be "1".
The remdsort works fine with this PARATEMP file but this could bring some confusion and avoidable mistakes in the future.

**Comment by ceriottm** [comment]
you mean that it prints after the first swap so it should be step 1?

**Comment by venkatkapil24** [comment]
I think that's what he means.

**Comment by litman90** [comment]
Well not exactly, because the first swap can happen at any step.
What I I mean is more general, the first column is just not consistent with the output files.
I attached some extract of input.xml, PARATEMP, and a particular output. 

[test.dat.zip](https://github.com/i-pi/i-pi/files/2801858/test.dat.zip)

Here it is evident the "-1 shift". In my understanding, the second column of PARATEMP ( the temperature of the md_0 ) should read:
0 (250 K)
2 (270 K)
1 (260K)
0 (...)
1
0
1
0
1
0
2

But it starts with a 2 and follows the sequence above

Again, the remdsort.py script works fine with this PARATEMP file but this could bring some confusion and avoidable mistakes in the future.

**Comment by ceriottm** [comment]
Any progress on this? Do you confirm there is indeed a bug, or shall I close this issue?

**Comment by litman90** [comment]
Since remdsort.py script gives the correct results at the end I would not call it a bug. You can close this issue.
