### ISSUE TITLE
NpT

### ISSUE THREAD

**Issue by tonypaxton** [i-pi/i-pi#15]
I am using i-PI in the forcefield='tbe-i-pi' branch. One of my sponsors is interested in air/steam mixtures at very high pressure and temperature.  It will be very interesting to find to what extend the water dissociates. To begin with I am experimenting with water at 300K and 1bar. I have set the barostat as in the examples/lm/h2o-bulk directory. I am wondering why there is such a huge fluctuation in the internal pressure: at each 1fs time-step it changes by as much as 10^6 bar. After some time-steps I have stopped the MD and I notice that in the RESTART file the barostat and thermostat parameters have been altered. For example the tau-value is increased from 200fs to ~10^4fs. I have now restarted using the RESTART file as input. Can I assume that this restarted MD is using the new barostat and thermostat parameters, and that the first run was using my initial values; or are these parameters continuously updated during an MD run? Should I be setting a piston momentum to try and dampen the pressure fluctuations?

Tony Paxton

**Comment by ceriottm** [comment]
Hi Tony, that's a fantastic application and make sure you check out the first i-PI comp phys comm paper as we do supercritical water at TPa pressure, which is very interesting. 

Before I answer your question, make sure that you are looking at things in the right units. i-Pi has a hardcore "everything is atomic units" policy. for convenience you can set up the inputs in whatever units, and you can request outputs to be printed out in whatever units. however, if you don't specify it explicitly it will use atomic units. so for sure in the RESTART file those parameters are in atomic units of time (about 200 times larger than fs) and it's very much possible that the pressure is in atomic units of pressure. in which case those fluctuations would be even more worrying.

**Comment by tonypaxton** [comment]
Dear Michele

Thanks, that explains the barostat time: it's the same as 200fs in a.u.; but the pressure is being printed in the output file in bar. For example,

$ head -25 t300p1.out
# column   1     --> step : The current simulation time step.
# column   2     --> time{picosecond} : The elapsed simulation time.
# column   3     --> conserved : The value of the conserved energy quantity per bead.
# column   4     --> temperature{kelvin} : The current temperature, as obtained from the MD kinetic energy.
# column   5     --> kinetic_cv : The centroid-virial quantum kinetic energy of the physical system.
# column   6     --> potential : The physical system potential energy.
# column   7     --> kinetic_cv(H) : The centroid-virial quantum kinetic energy of the physical system.
# column   8     --> kinetic_cv(O) : The centroid-virial quantum kinetic energy of the physical system.
# column   9     --> pressure_cv{bar} : The quantum estimator for pressure of the physical system.
# column  10     --> density{g/cm3} : The mass density of the physical system.
    0.00000000e+00     0.00000000e+00    -5.67865800e+01     2.82582135e+02     5.47225667e-01    -5.72942307e+01     3.64817111e-01     1.82408556e-01    -6.03117229e+03     9.82690999e-01
    1.00000000e+00     1.00000000e-03    -5.67801581e+01     2.49544268e+02     5.47225667e-01    -5.72306505e+01     3.64817111e-01     1.82408556e-01    -3.87775472e+03     9.82744776e-01
    2.00000000e+00     2.00000000e-03    -5.67709675e+01     1.98247520e+02     5.47225667e-01    -5.71324059e+01     3.64817111e-01     1.82408556e-01    -2.64914692e+03     9.82871127e-01
    3.00000000e+00     3.00000000e-03    -5.67747509e+01     1.88964907e+02     5.47225667e-01    -5.71227234e+01     3.64817111e-01     1.82408556e-01    -6.33857883e+03     9.83023702e-01
    4.00000000e+00     4.00000000e-03    -5.67808928e+01     2.00545429e+02     5.47225667e-01    -5.71543107e+01     3.64817111e-01     1.82408556e-01    -1.18199378e+04     9.83263404e-01
    5.00000000e+00     5.00000000e-03    -5.67807231e+01     1.91273833e+02     5.47225667e-01    -5.71333715e+01     3.64817111e-01     1.82408556e-01    -1.27182719e+04     9.83725127e-01
    6.00000000e+00     6.00000000e-03    -5.67753613e+01     1.58321736e+02     5.47225667e-01    -5.70607138e+01     3.64817111e-01     1.82408556e-01    -8.51453626e+03     9.84426143e-01
    7.00000000e+00     7.00000000e-03    -5.67706314e+01     1.39429007e+02     5.47225667e-01    -5.70171223e+01     3.64817111e-01     1.82408556e-01    -3.57808840e+03     9.85245880e-01
    8.00000000e+00     8.00000000e-03    -5.67768638e+01     1.62508184e+02     5.47225667e-01    -5.70627761e+01     3.64817111e-01     1.82408556e-01    -1.74901573e+03     9.86152364e-01
    9.00000000e+00     9.00000000e-03    -5.67827968e+01     1.79494351e+02     5.47225667e-01    -5.71067324e+01     3.64817111e-01     1.82408556e-01    -1.32414198e+03     9.87070709e-01
    1.00000000e+01     1.00000000e-02    -5.67785874e+01     1.64177745e+02     5.47225667e-01    -5.70672060e+01     3.64817111e-01     1.82408556e-01     3.00940664e+01     9.88023713e-01

.
.
.
.
.

$ tail -f t300p1.out-1
    6.84590000e+04     6.84590000e+01    -5.09389564e+01     2.89573786e+02     5.47225667e-01    -5.76688106e+01     3.64817111e-01     1.82408556e-01     2.24448415e+03     1.23470084e+00
    6.84600000e+04     6.84600000e+01    -5.09432029e+01     2.87295286e+02     5.47225667e-01    -5.76766475e+01     3.64817111e-01     1.82408556e-01    -1.27981528e+03     1.23476696e+00
    6.84610000e+04     6.84610000e+01    -5.09457796e+01     2.82158986e+02     5.47225667e-01    -5.76742977e+01     3.64817111e-01     1.82408556e-01    -4.13694130e+03     1.23488124e+00
    6.84620000e+04     6.84620000e+01    -5.09475451e+01     2.83433246e+02     5.47225667e-01    -5.76732639e+01     3.64817111e-01     1.82408556e-01    -4.83089563e+03     1.23511604e+00
    6.84630000e+04     6.84630000e+01    -5.09495016e+01     2.85748696e+02     5.47225667e-01    -5.76821704e+01     3.64817111e-01     1.82408556e-01    -3.60337503e+03     1.23542707e+00
    6.84640000e+04     6.84640000e+01    -5.09499782e+01     2.89441277e+02     5.47225667e-01    -5.76981493e+01     3.64817111e-01     1.82408556e-01    -8.61581926e+02     1.23578990e+00
    6.84650000e+04     6.84650000e+01    -5.09512954e+01     2.96619954e+02     5.47225667e-01    -5.77104296e+01     3.64817111e-01     1.82408556e-01     2.73718637e+03     1.23615609e+00
    6.84660000e+04     6.84660000e+01    -5.09505119e+01     2.95496227e+02     5.47225667e-01    -5.77076687e+01     3.64817111e-01     1.82408556e-01     5.35678858e+03     1.23647616e+00
    6.84670000e+04     6.84670000e+01    -5.09497705e+01     2.93019030e+02     5.47225667e-01    -5.76956112e+01     3.64817111e-01     1.82408556e-01     6.27566963e+03     1.23667992e+00
    6.84680000e+04     6.84680000e+01    -5.09520749e+01     2.90907742e+02     5.47225667e-01    -5.76946385e+01     3.64817111e-01     1.82408556e-01     3.75246582e+03     1.23683283e+00
    6.84690000e+04     6.84690000e+01    -5.09541625e+01     2.92086800e+02     5.47225667e-01    -5.77024555e+01     3.64817111e-01     1.82408556e-01    -8.48845741e+02     1.23688380e+00
    6.84700000e+04     6.84700000e+01    -5.09537286e+01     2.91192851e+02     5.47225667e-01    -5.77028946e+01     3.64817111e-01     1.82408556e-01    -4.84706112e+03     1.23696684e+00
    6.84710000e+04     6.84710000e+01    -5.09545948e+01     2.87485170e+02     5.47225667e-01    -5.76944666e+01     3.64817111e-01     1.82408556e-01    -5.74429831e+03     1.23716508e+00
    6.84720000e+04     6.84720000e+01    -5.09548881e+01     2.84937376e+02     5.47225667e-01    -5.76839473e+01     3.64817111e-01     1.82408556e-01    -3.54054802e+03     1.23747851e+00

I would have hoped that the density was a bit closer to 1.

Tony

**Comment by tonypaxton** [comment]
Sorry for the funny formatting: I cut and pasted from my unix "screen" ...

**Comment by ceriottm** [comment]
Uhm... I fear that if the density is so high it's not the fault of the
barostat... TIP4P and MB-POL both give densitites in agreement with
literature results.
The conserved quantity seems not very well conserved, but other than that
from what I see everything seems legit.
Michele
