### ISSUE TITLE
PLUMED not evoked when using MTS

### ISSUE THREAD

**Issue by MoleOrbitalHybridAnalyst** [i-pi/i-pi#166]
Hi,

When using MTS, plumed seems cannot be evoked by ffplumed normally. Here is an example input to reproduce the problem:

```xml
 <simulation mode='md' verbosity='high'>

  <output prefix='simulation'>
    <properties stride='1' filename='out'>  [ step, time{picosecond}, conserved, temperature{kelvin}, kinetic_cv, potential, pressure_cv{megapascal} ] </properties>
    <trajectory filename='pos' stride='1'> positions </trajectory>
    <checkpoint stride='200'/>
  </output>
  <total_steps>10</total_steps>
  <prng>
    <seed>31415</seed>
  </prng>
  <ffsocket name='lmp_short' mode='unix'>
    <address>h2o-pimd+mts.4_short</address>
  </ffsocket>
  <ffsocket name='lmp_long' mode='unix'>
    <address>h2o-pimd+mts.4_long</address>
  </ffsocket>
  <ffplumed name="plumed">
        <init_file mode="xyz">init.xyz</init_file>
        <plumeddat> plumed.dat </plumeddat>
  </ffplumed>
  <system>
    <initialize nbeads='4'>
      <file mode='pdb'> init.pdb </file>
      <velocities mode='thermal' units='kelvin'> 300 </velocities>
    </initialize>
    <forces>
       <!--
         MTS setup - apply the fast (short-range) force in the inner loop and the slow (long-range) force in the outer loop.
         Note that if the outer loop contains a *correction* to the inner loop the weights should be
         [-1,1] (fast force) and [1,0] (slow force)
       -->
      <force forcefield='lmp_short'>
        <mts_weights>[0,1]</mts_weights>
      </force>
      <force forcefield='lmp_long'>
        <mts_weights>[1,0]</mts_weights>
      </force>
    </forces>
    <motion mode='dynamics'>
      <dynamics mode='nvt'>
        <timestep units='femtosecond'> 2.00 </timestep>
        <thermostat mode='langevin'>
          <tau units='femtosecond'> 100 </tau>
        </thermostat>
        <nmts>[1,4]</nmts>
      </dynamics>
    </motion>
    <ensemble>
      <temperature units='kelvin'> 300 </temperature>
    </ensemble>
  </system>
<!--
  <smotion mode="metad">
     <metad> <metaff> [ plumed ] </metaff> </metad>
  </smotion>
-->
</simulation>
```

The above input was modified from the example under examples/lammps/h2o-pimd+mts.4. The plumed.dat is a simple one that prints out the distance of atom 1 and 2 in COLVAR 

"
FLUSH STRIDE=1

d: DISTANCE ATOMS=1,2

PRINT ARG=d FILE=COLVAR  STRIDE=1
"

Whenever I turn on or off the smotion section, I **can** see i-pi call the plumed python module (PLUMED parsing information printed out) and I **do** get a COLVAR file, but the COLVAR file is always empty. I think the plumed calculation is not actually evoked during the MD run (a missing plumed_cmd sentence in i-pi MTS integrator maybe?)  but only plumed initialization is correctly called.

BTW, I have no problem of using plumed if turn off MTS, so the problem should be in the MTS integrator part, I think.

**Comment by MoleOrbitalHybridAnalyst** [comment]
Sorry, the xml was not correctly formatted. Now it looks fine.

**Comment by ceriottm** [comment]
It's actually bizarre you get an output when you run without MTS. Why would PLUMED be called, when the plumed force is used nowhere?

**Comment by MoleOrbitalHybridAnalyst** [comment]
> It's actually bizarre you get an output when you run without MTS. Why would PLUMED be called, when the plumed force is used nowhere?

Good question.. I double checked my inputs. Looks like I messed up with an input with <bias> and another without <bias>. Now problem solved. Thanks!!
