### ISSUE TITLE
Possibility of forcing assignment of a particular replica to a matching client

### ISSUE THREAD

**Issue by Taylor-96** [i-pi/i-pi#172]
Hi, I'm just opening this issue as suggested so that we can discuss further the possibility of including a forced matching mode in i-pi for those driver codes that could perhaps benefit from its availability.

**Comment by ceriottm** [comment]
So, I am very much in favor of the idea and to me the main issue is defining clearly what we should do (1) if the clients don't arrive all at the same time and (2) if one of the clients die / become unresponsive. Perhaps it would help if you start by describing the specifics of the use case you have in mind.

**Comment by Taylor-96** [comment]
Great! Just to be sure what you mean by your first point - are you referring to the situation where some of the drivers are faster to perform their task and so arrive at an idle state while the other drivers are still computing the forces/PE? I guess that in the normal situation of automatic matching where free drivers are allowed to be reassigned, the potential of excessive idling would be avoided (if the number of replicas>number of drivers otherwise this would be an unavoidable bottleneck, no?). However, in the forced matching situation, I think it would be necessary to always have the number of drivers = the number of replicas - otherwise the alternative of modifying the client code to deal with the correct assignment would be necessary I believe. The more we discuss this, the more this latter solution does seem to be the most flexible approach - I may have just been lucky in the case I'm looking at that the hacky work-around I mentioned got the job done.

With regard to your point (2), I think the solution that Mariana and yourself proposed whereby a clean exit of both i-pi and driver is made upon hanging of one of the clients (with the latter ensuring the recording of electronic density coefficients and the corresponding replica ID in a restart file) would be the direction to go in.

In terms of the specifics of the use-case I'm looking at: I had been working to couple i-pi with a code based on a scheme developed by Sara Bonella and company called mass-zero constrained dynamics (Phys. Chem. Chem. Phys., 2020, 22, 10775-10785). The code itself works with orbital-free DFT and it requires that the density coefficients be propagated via constrained MD (thus these electronic density coefficients are active degrees of freedom). The problem therefore arose that when we attempted to carry out the nuclear propagation via i-pi, sometimes a given replica was passed to the wrong client (i.e. one which stored density coefficients which were computed based on a different replica's geometry). This therefore lead to a lack of consistency in the electronic density coefficients and it appeared that this issue manifested itself in negative density coefficients. After forcing i-pi to carry out strict driver-replica matching this issue was rectified. Although the negative density issues would be specific to OF-DFT, I can imagine that the potential mismatching of clients and replicas in CPMD using KS-DFT could present a similar issue in terms of inconsistency.

**Comment by mahrossi** [comment]
This has been addressed with a recent merge. #175
