### ISSUE TITLE
Upgrade regtest infrastructure to allow the possibility of specifying meaningful tolerances

### ISSUE THREAD

**Issue by litman90** [i-pi/i-pi#181]
**Problem:** 

Many tests fails because tolerances are not adequate.

**Proposed solution (as agreed in the slack channel, March 4):**

1) Add 2 columns, an absolute and relative tolerance in the files_to_check.txt.. this will also allow setting different tolerances for structures, or energy outputs.

2)  For algorithms that exist by checking a condition like geop, instanton, etc.
The regtest should look for converged structure and properties files to check that the actual calculation finished and finished correctly.
("correctly" here must mean "equivalent for practical purposes".)

**Comment by mahrossi** [comment]
I think we already addressed this but forgot to close the issue. Can you confirm @litman90 ?
