### ISSUE TITLE
Property logging on one line

### ISSUE THREAD

**Issue by sirmarcel** [i-pi/i-pi#184]
Hello, a quick oddity: 

When I add
```
<properties stride='1' filename='out' flush='1'>  [ step, time{picosecond}, conserved, temperature{kelvin}, potential{eV}] </properties>
```
to `input.xml`, the `.out` file produced contains all data on a single line, i.e. the newline between steps is missing.

This doesn't happen if I use:

```
<properties stride='1' filename='out' flush='1'>  [ step, time{picosecond}, conserved, temperature{kelvin}] </properties>
```

In other words, if I simply drop one property (it doesn't matter which one), this doesn't occur. 

Here's a reproducing example, at least on my machine (macOS), using the `ase` `LennardJones` calculator. (I don't actually use it for production, but the calculator I'm using is not yet open source, so I can't include it. ;) )

[output_error.zip](https://github.com/i-pi/i-pi/files/6206591/output_error.zip)

**Comment by sirmarcel** [comment]
Ah, I found out why -- the `{eV}` unit for `potential` is the culprit.

**Comment by sirmarcel** [comment]
Feel free to close as user error!

**Comment by ceriottm** [comment]
I'll close it, but this is one of the many places where (helpful) error messages would be useful
