### ISSUE TITLE
Is it possible to connect i-pi with TDDFT software like Octopus?

### ISSUE THREAD

**Issue by Satinelamp** [i-pi/i-pi#213]
I am wondering if it is possible to connect i-ip with octopus(https://octopus-code.org/). 
Octopus is a TDDFT software, which lacks the support of nuclei quantum effect. I am wondering if it is possible to make it work together with i-pi?

**Comment by ceriottm** [comment]
There isn't an interface implemented for octopus, but it's easy enough to write one. You can look at one of the many codes that implement a socket interface. Alternatively (but with substantial performance penalty) you could run it using ASE as a man in the middle.

**Comment by mahrossi** [comment]
If Octopus can communicate with ASE through sockets, the performance penalty for using ASE as a person-in-the-middle is not too large.

**Comment by ceriottm** [comment]
I'm closing this because it is really an issue in Octopus. @Satinelamp  feel free to re-open if there is something needed on the i-PI side
