### ISSUE TITLE
ipi_global_settings overridden by default behaviour in inputs/simulations.py

### ISSUE THREAD

**Issue by cbenmahm** [i-pi/i-pi#215]
Hi,

I tried changing the number of the significant digits that are printed to the output file of i-pi by modifying ``ipi_global_settings`` in ``ipi/__init__`` as maybe hinted to when looking at the implementation of the function ``write_type`` in ``ipi/utils/io/inputs/io_xml.py`` . However this was not successful and the output always has 8 significant digits. I found out that it was possible to change the significant digits by changing a "default" behavior in  ``floatformat`` in  ``ipi/inputs/simulation.py`` (line 128).

Is there a reason for this behavior or am I missing something important?

Thank you in advance for help!

--Chiheb

**Comment by mahrossi** [comment]
I think I will close this issue because it is not relevant anymore? Indeed the way to go would be to specify the attribute floatformat in the input file, so you can control which precision and formatting you want for different parts.
