### ISSUE TITLE
Questions for repilca exchange BOMD using CP2K

### ISSUE THREAD

**Issue by yunjian-hash** [i-pi/i-pi#216]
Dear developers,

Sorry for the wrong place to ask these questions because I can not raise questions in form now.
1. Is there any tutorials about how to analyse the trajectories of REMD? where is the script to reorder the trajectories?
2. If I want to do repilca exchange BOMD, how many beads should I use?
3.  In CP2K, there is a section named MOTION, where I can set the ensemble and thermostat information for MD. So, if I have set the nvt ensemble and thermostat type in cp2k's input file, should I still need to set the ensemble and thermostat in i-pi input? besides, what is  the meaning of the section A, B and C, and the numbers in the attached picture?

Looking forward for your kind reply, thanks!

![6Y7 R3WGN$95HE8A5%@ G{E](https://user-images.githubusercontent.com/75162924/177164893-eb60b6ec-bd8a-4701-93eb-5e5f5c755781.png)

**Comment by ceriottm** [comment]
Can you write this as a question on the [user forum](https://ipi-code.org/resources/forum/)? we try to keep questions on usage there and have GH for bugs/development.
