### ISSUE TITLE
The essential tag to distinguish the classical MD and PIMD

### ISSUE THREAD

**Issue by weotao** [i-pi/i-pi#222]
Hi,
The are two examples in i-pi/examples/VASP/, **water-1-npt-md-vasp** and **dia-npt-pimd-vasp**, [https://github.com/i-pi/i-pi/tree/master/examples/VASP](url). Does it means to use i-pi with VASP to do Classical molecular Dynamics for water and do Path Integral Molecular Dynamics ?
Analyze the two input files sentence by sentence, I can't clear which tag could distinguish the MD and PIMD.
It's a difficult things to learn PIMD from beginning!!!Thanks very much for help from Github.
The two input files as follows:
[dia-npt-pimd-vasp-input.txt](https://github.com/i-pi/i-pi/files/9200063/dia-npt-pimd-vasp-input.txt)
[water-1-npt-md-vasp-input.txt](https://github.com/i-pi/i-pi/files/9200064/water-1-npt-md-vasp-input.txt)
Regards,
weitao

**Comment by ceriottm** [comment]
Hello. I added you to the forums, do you mind repeating the question there? We try to keep github for bugreports and development, and the forum for usage questions.
Thanks

**Comment by ceriottm** [comment]
Hello. I added you to the forums, do you mind repeating the question there?
We try to keep github for bugreports and development, and the forum for
usage questions.
Thanks
