### ISSUE TITLE
Different trajectories from lammps and I-PI

### ISSUE THREAD

**Issue by changxiaoju** [i-pi/i-pi#230]
I do PIMD using i-pi with lammps.
I have 8 beads and 8 xyz position files and a centriod file, and all of them are very different from trajectory dumped by lammps. Is it normal? Which trajectory should i believe?
Meanwhile, the thermo information dumped by lammps and i-pi are the same.
the
i-pi input file:
`<trajectory filename='pos' stride='1000' format='xyz' cell_units='angstrom'>positions{angstrom} </trajectory>`
`positions{angstrom} </trajectory>`
i have tried pbc='True' and pbc='False'
lammps input file:
`variable NSTEPS equal 4000002`
`dump trj all atom 10000 out.lammpstrj`

very different trajectories:
(left dumped by lammps, right is the xyz file from i-pi (wraped at PBC))
Is there anything wrong with the communication of coordinate between lammps and i-pi? And it seems xyz file from i-pi also very strange because the box keeps getting larger and larger and larger...
![c99f3a6a979769630397673522cecf1](https://user-images.githubusercontent.com/44628664/190941418-0b8a5044-9d1e-41c5-ad2d-73cd3661c122.png)

**Comment by ceriottm** [comment]
I suspect a mess-up with units. i-PI expects, unless otherwise specified, everything to be in atomic units. if you are using an xyz that is in angstrom in the initialization without specifying it's so, it will load it assuming it's in bohr and all hell will break loose.

**Comment by changxiaoju** [comment]
> I suspect a mess-up with units. i-PI expects, unless otherwise specified, everything to be in atomic units. if you are using an xyz that is in angstrom in the initialization without specifying it's so, it will load it assuming it's in bohr and all hell will break loose.
Thankyou for reply. But I have specified cell parameters in the initial xyz file like:
`9000
#  CELL(abcABC):   28.5 28.5 28.5 90.0  90.0  90.0 **cell{angstrom} positions{angstrom}**`
and in the input xml file 
` <file mode='xyz'> conf.xyz  </file>
  <cell mode='abc' units='angstrom'> [28.5,28.5,28.5] </cell>`
is that still not enough?
but I see example like `/i-pi/examples/lammps/graphene` no more settings on units

**Comment by changxiaoju** [comment]
> I suspect a mess-up with units. i-PI expects, unless otherwise specified, everything to be in atomic units. if you are using an xyz that is in angstrom in the initialization without specifying it's so, it will load it assuming it's in bohr and all hell will break loose.



> I suspect a mess-up with units. i-PI expects, unless otherwise specified, everything to be in atomic units. if you are using an xyz that is in angstrom in the initialization without specifying it's so, it will load it assuming it's in bohr and all hell will break loose.

**Comment by ceriottm** [comment]
Is the simulation stable (low drift, temperature and potential fluctuating around fixed mean value....)?
In all events it's probably easier to debug this if you upload a zip with all the files needed to run (xml, input xyz, lammps input and data files).

**Comment by changxiaoju** [comment]
Thank you ceriottm, the simulation is stable, the temperature, the pressure...
I upload a zip of mine. the error happens in the beginning, so you can kill if there is a second frame output of both lammps and i-pi to save your CPU time. Thanks again
[files.zip](https://github.com/i-pi/i-pi/files/9605719/files.zip)

**Comment by ceriottm** [comment]
So you solved this? Might be useful to explain what was the problem so others can benefit.

**Comment by changxiaoju** [comment]
yes, it is because the index of atoms in the data file for lammps are not a sequence, but out of order.
