### ISSUE TITLE
A sample system works in NVT simulation but fails in NPT simulation 

### ISSUE THREAD

**Issue by Jeremydream** [i-pi/i-pi#236]
Hello, I was trying to use i-pi as the interface to do bulk NPT simulation in my system, but it can not work after few steps and failed in NPT simulation; I don't know where the problem is, but I want to know whether there is a problem in the input.xml. And then here is the code:

[input.xml.txt](https://github.com/i-pi/i-pi/files/10148878/input.xml.txt)

**Comment by ceriottm** [comment]
hm. in which way does it fail? cell blows up? are you positive that the drivers you are using are computing (and/or passing) the virial properly? that's where I'd start debugging. 
use a very small time step and see if the conserved quantity is conserved - if it is in NVT but not in NPT, I'd put my money on "broken virial sent from the driver".

**Comment by Jeremydream** [comment]
After a few steps, the molecule will break, it shows as the hydrogen atom or some other small molecules have been generated from the long-chain PEG molecule, like the picture shows.
Now I've tried in 0.5 fs timestep, it still does not works.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/72368464/205594896-e6cbd8cc-fe05-4796-8f09-34a7d5a02845.png">

**Comment by Jeremydream** [comment]
Hello, ceriottm. I've founded out why the phenomenon happened, as the method you mentioned. Maybe there is not enough repulsion description within a closed distance between hydrogen bonding with the constructed machine-learning potential. Do you know if there are any methods to complement the repulsion description under the i-Pi framework? 
Thanks a lot.

**Comment by ceriottm** [comment]
The easiest way is to create a repulsive potential in say LAMMPS, and use it either together with your ML potential (if it's also implemented in LAMMPS) or as a separate <forcefield> entry.

**Comment by Jeremydream** [comment]
Thanks a lot. 
After a long time of trying to repeat what you said, it works. I've reproduced the LJ repulsion by the JAX framework as the complement for my hybrid force field. It can run a period of time anyway, but the "breaking" question still remains. Could you recommend some classical bulk NPT simulations by using i-Pi?

**Comment by ceriottm** [comment]
Uhm... all examples in `examples/lj` are classical NPT (or variable-cell NST) simulations. You can take those as "reasonable" examples. Cheers.
