### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by ianhbell** [i-pi/i-pi#237]
Took me a second to realize that I needed to be in ``drivers/f90`` before I could run the ``make``. Should the README be updated?

**Comment by litman90** [comment]
Thanks for your message.
Do you mind creating a PR with the modifications you find more suitable?

**Comment by ianhbell** [comment]
See https://github.com/i-pi/i-pi/pull/238

**Comment by ceriottm** [comment]
Fixed by #238
