### ISSUE TITLE
New implementation of bosonic PIMD

### ISSUE THREAD

**Issue by yotamfe** [i-pi/i-pi#249]
Hi!

@BarakHirshberg and I are working on a new, faster implementation of bosonic path integral molecular dynamics.
It is developed in [this clone ](https://github.com/yotamfe/i-pi) (the directory "bench_bosons" will be removed of course).

Towards this goal, we have a few questions:

1. We would like to add a test for the boson PIMD functionality. What would make most sense? A regression test for a few steps ensuring that the resulting energies and xyz data are as expected, for a specified seed? Or something else? How long is it reasonable for such a test to run?

2. During development we noticed a small potential issue without output files, where, in the output file, the comments at the beginning of the file describing the column headers sometimes doesn't print the column number, generating lines such as
\# column        --> virial_fq : The scalar product of force and position.
instead of e.g.
\# column 7       --> virial_fq : The scalar product of force and position.
This happens when the property specifies "size" explicitly but that size is 1. In our clone we modified the code to produce a number also in this case (see commit [e6c4b5](https://github.com/yotamfe/i-pi/commit/d9051d80c4a245fedd42ee3b350e26548de6c4b5) in our clone), since otherwise code that parses that table based on the headers (akin to [getproperty.py](https://github.com/i-pi/i-pi/blob/master/tools/py/getproperty.py)) gets confused.
Is this a change you would like to incorporate too? If so, would you like it in a separate pull request?

3. Anything else that we should pay special attention to?

Thanks!

**Comment by BarakHirshberg** [comment]
@ceriottm @mahrossi @litman90 @venkatkapil24

**Comment by ceriottm** [comment]
Hi! Thanks for your contribution

> @BarakHirshberg and I are working on a new, faster implementation of bosonic path integral molecular dynamics. It is developed in [this clone ](https://github.com/yotamfe/i-pi) (the directory "bench_bosons" will be removed of course).
> 
> Towards this goal, we have a few questions:
> 
> 1. We would like to add a test for the boson PIMD functionality. What would make most sense? A regression test for a few steps ensuring that the resulting energies and xyz data are as expected, for a specified seed? Or something else? How long is it reasonable for such a test to run?

Usually we expect an example that runs whatever you want (and is run during testing with a dummy driver and for a single step, just to check that there are no errors) and a regtest, that actually does the real thing and is checked against a reference. Note however the refactoring of the examples we are planning, #245 

> 2. During development we noticed a small potential issue without output files, where, in the output file, the comments at the beginning of the file describing the column headers sometimes doesn't print the column number, generating lines such as
>    # column        --> virial_fq : The scalar product of force and position.
>    instead of e.g.
>    # column 7       --> virial_fq : The scalar product of force and position.
>    This happens when the property specifies "size" explicitly but that size is 1. In our clone we modified the code to produce a number also in this case (see commit [e6c4b5](https://github.com/yotamfe/i-pi/commit/d9051d80c4a245fedd42ee3b350e26548de6c4b5) in our clone), since otherwise code that parses that table based on the headers (akin to [getproperty.py](https://github.com/i-pi/i-pi/blob/master/tools/py/getproperty.py)) gets confused.
>    Is this a change you would like to incorporate too? If so, would you like it in a separate pull request?

This seems like a perfect bugfix PR. Please do it as a separate PR to avoid conflating new features and bugfixes.

> 3. Anything else that we should pay special attention to?

We are also refactoring the documentation, #169, so the helpstring that are defined in the input file will be pulled into the input reference. Make sure you use brief but informative text. Can't say that everything is brief and informative at the moment, but at least let's try to do well with new features ^_^
> 
> Thanks!
