### ISSUE TITLE
Add Readme file to VASP path

### ISSUE THREAD

**Issue by litman90** [i-pi/i-pi#252]
The PR https://github.com/i-pi/i-pi/pull/250 was merged without providing a README file.
@venkatkapil24, since you merge it,  could you take care of adding a description?

**Comment by venkatkapil24** [comment]
Hey Yair, can you clarify this further, especially "VASP path"? There is a README in i-pi/examples/VASP/
Do you want another one somewhere else?

**Comment by litman90** [comment]
My bad, I couldn't find it  ( I was looking in the incorrect place) but now I see the README file. Thanks.
