### ISSUE TITLE
example/ph2/rpmd lack of input.xml

### ISSUE THREAD

**Issue by PepeBelisarius** [i-pi/i-pi#264]
# this rule creates a run_% subdirectory of rpmd, and executes 16 rpmd runs in it,
# always restarting from the previous run with randomized velocities.
rpmd/run_%/test16.out: 
	cd rpmd; mkdir -p run_$*; cp start-$*.chk run_$*/RESTART; \
	for x in `seq 1 16`; do \
	  sed "s/YYY/"$*"/; s/XXX/$$x/;" input.xml > run_$*/input.xml; \
	  $(IPI) run_$*/input.xml & sleep 25; \
	  $(call run_driver,8,run-$*-$$x); wait; \
	  mv RESTART run_$*/; \
	done  

The Makefile is written in such a way that it appears to require the input.xml file from the rpmd folder using 'sed' command and output it to the run_% folder. However, the input.xml file is not present in the rpmd folder.

Can you provide us with the input.xml file, or should I write the file myself for this part?

**Comment by mahrossi** [comment]
Hey Pepe, sorry for the late reply. Could you tell us which example exactly you were trying to run?

**Comment by PepeBelisarius** [comment]
I want to run the example/ph2/rpmd.

Under the directory "example/ph2/," the included Makefile contains instructions for executing the simulation, encompassing code for computing the velocity-velocity autocorrelation function. However, direct execution of this simulation is unattainable. As previously stated, the "rpmd" folder lacks the "input.xml" file.

**Comment by ceriottm** [comment]
I made an input.xml file just so it's not broken, but we should decide whether the whole ph2 folder has some value or should be forgotten.
