### ISSUE TITLE
NEB not working?

### ISSUE THREAD

**Issue by litman90** [i-pi/i-pi#269]
Hi @mahrossi @fidanyan , 

I was testing the NEB functionality, to move it from examples/temp/neb  to examples/features but it is breaking before converging.

I got the following:

[...]
 @DampedBFGS: Update of the Hessian, no damping.
 @DampedBFGS: (s_k dot y_k) before reciprocating: 4.413497e-04
 @NEB: after Damped_BFGS() call
 @NEBMover: increasing big_step to 2.087957 bohr.
 @NEB: bead positions transferred from mapper.
Bead  1, distance to previous bead:   0.429303
Bead  2, distance to previous bead:   0.427729
Bead  3, distance to previous bead:   0.427298
Bead  4, distance to previous bead:   0.425591
Bead  5, distance to previous bead:   0.431845
Bead  6, distance to previous bead:   0.431268
Bead  7, distance to previous bead:   0.423269
Bead  8, distance to previous bead:   0.424344
Bead  9, distance to previous bead:   0.427493
Bead 10, distance to previous bead:   0.419032
Bead 11, distance to previous bead:   0.411709
Bead 12, distance to previous bead:   0.417621
Bead 13, distance to previous bead:   0.407921
Bead 14, distance to previous bead:   0.408710
Bead 15, distance to previous bead:   0.408792
 @NEB: NEB forces transferred from mapper.
WARNING: No extras information has been passed.
 @NEB: remaining max force component: 0.007002392657179345
 @NEB: max delta x: 0.008290871001838562
 @NEB: Not converged, deltaEnergy = 0.00000047, tol = 0.00000367 per atom
 @NEB: Not converged, nebgrad = 0.00700239, tol = 0.000194
 @NEB: Not converged, deltaX = 0.00829087, tol = 0.00100000
 # Average timings at MD step      10. t/step: 5.94703e-01
Error reading from socket: server has quit or connection broke: Success

Is it working for you?

Best,
Yair

**Comment by mahrossi** [comment]
Hi Yair, for me it converged after 208 steps:

>  @DampedBFGS: (s_k dot y_k) before reciprocating: 1.731193e-07
 @DampedBFGS: stabilizing the diagonal of the Hessian.
 @NEB: after Damped_BFGS() call
 @NEBMover: Step direction far from nebgrad/climbgrad, reducing big_step to 0.020000 bohr.
 @NEB: bead positions transferred from mapper.
Bead  1, distance to previous bead:   0.575317
Bead  2, distance to previous bead:   0.575323
Bead  3, distance to previous bead:   0.575316
Bead  4, distance to previous bead:   0.575290
Bead  5, distance to previous bead:   0.575233
Bead  6, distance to previous bead:   0.575186
Bead  7, distance to previous bead:   0.575138
Bead  8, distance to previous bead:   0.575082
Bead  9, distance to previous bead:   0.575023
Bead 10, distance to previous bead:   0.574972
Bead 11, distance to previous bead:   0.574940
Bead 12, distance to previous bead:   0.574932
Bead 13, distance to previous bead:   0.574964
Bead 14, distance to previous bead:   0.574981
Bead 15, distance to previous bead:   0.574995
 @NEB: NEB forces transferred from mapper.
WARNING: No extras information has been passed.
 @NEB: remaining max force component: 7.673266926434765e-05
 @NEB: max delta x: 0.000987358893086654
============================================================
 @NEB: path optimization converged. Step: 208
============================================================

 # Average timings at MD step     208. t/step: 3.83491e-01
 # DEBUG # Top 10 memory allocations:

**Comment by mahrossi** [comment]
Just to be clear: that was in `examples/temp/pes/neb` -- which Karen added.

**Comment by litman90** [comment]
Thanks, Mariana for testing it.

Could you tell me which Numpy version are you using?

**Comment by mahrossi** [comment]
Yes, I am not sure which version I had in my work computer, but I just ran again in my home computer where it is numpy 1.24.2 and it also runs and converges to the same result in the same number of iterations. Just one thing I noticed: that input file has the `verbosity=debug` flag on, which seems to enter some places in the code that are not very maintained. Can you change to verbosity=low and try again? Then of course, the numpy version should also help.

**Comment by litman90** [comment]
Thanks again.
The verbosity doesn't change the outcome but the numpy version does. 
I added in the corresponding README.md a message on this regard.

**Comment by mahrossi** [comment]
thanks!

**Comment by fidanyan** [comment]
Hi @litman90, I remember there was a problem in reciprocating the Hessian matrix, which appeared in some Numpy versions but not in others. I didn't find why it happened, but the code has changed since I had this problem: I added checks for condition number and stabilized the matrix in case there are small eigenvalues, so it shouldn't be singular. So, I don't know what's the problem now.
