### ISSUE TITLE
i-PI with cp2k: Timeout in getforce, trying again!

### ISSUE THREAD

**Issue by npavlovikj** [i-pi/i-pi#273]
Hi,

I am trying to run `i-pi/2.4` with `cp2k/9.1` on our HPC cluster. 
I am using the examples given [here](https://github.com/zerothi/i-pi-dev/tree/master/examples/cp2k) and [here](https://github.com/i-pi/tutorials-schools/tree/main/tutorial-1/ex-2).

I tried both the UNIX and the INET sockets, and while the `cp2k` jobs continue running, I am always getting:
```
 @SOCKET:   Client asked for connection from ('10.133.23.5', 44748). Now hand-shaking.
 @SOCKET:   Handshaking was successful. Added to the client list.
 @SOCKET: 23/09/06-14:32:19 Assigning [ none] request id    0 to client with last-id None (  0/  1 : ('10.133.23.5', 44748))
 !W!  @SOCKET:   Timeout in getforce, trying again!
 @SOCKET: 23/09/06-14:32:20 Assigning [match] request id    0 to client with last-id    0 (  0/  1 : ('10.133.23.5', 44748))
 !W!  @SOCKET:   Timeout in getforce, trying again!
 # Average timings at MD step       0. t/step: 7.83768e-01
 @SOCKET: 23/09/06-14:32:21 Assigning [match] request id    0 to client with last-id    0 (  0/  1 : ('10.133.23.5', 44748))
```
in the `i-pi` log file.

Because of this, I am not sure if the `cp2k` runs are actually integrated with `i-pi`.

Can you please let me know what is the reason for the `Timeout` message, and how I can fix it?

Thank you,
Natasha

**Comment by ceriottm** [comment]
This is OK, it can depend on the communication patterns and the details of the calculation. If there are too many of these, the connection with cp2k may break (and then the simulation will be on hold until you relaunch cp2k) but otherwise everything will run and results will be fine. It's just a warning.
