### ISSUE TITLE
Can I run i-PI in parallel?

### ISSUE THREAD

**Issue by M0h4amad** [i-pi/i-pi#274]
I want to make sure that i-PI is running optimally on my cluster. I noticed that i-PI is running as a serial job. Can it be run in parallel like the CP2K client connected to it?

**Comment by M0h4amad** [comment]
**Below you can find the details of the node the job is running on. I am using exactly 20 cores of that node.**

NodeName=c2013 Arch=x86_64 CoresPerSocket=28 
   CPUAlloc=26 CPUTot=56 CPULoad=20.36
   AvailableFeatures=cx6,ib_verbs,ib_2xhdr,ib_100
   ActiveFeatures=cx6,ib_verbs,ib_2xhdr,ib_100
   Gres=(null)
   NodeAddr=c2013 NodeHostName=c2013 Version=20.11.9
   OS=Linux 4.18.0-477.21.1.el8_8.x86_64 #1 SMP Thu Aug 10 13:51:50 EDT 2023 
   RealMemory=250000 AllocMem=222992 FreeMem=161237 Sockets=2 Boards=1
   State=MIXED ThreadsPerCore=1 TmpDisk=0 Weight=250 Owner=N/A MCS_label=N/A
   Partitions=batch 
   BootTime=2023-08-23T11:06:05 SlurmdStartTime=2023-09-07T12:05:17
   CfgTRES=cpu=56,mem=250000M,billing=62
   AllocTRES=cpu=26,mem=222992M
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
   Comment=(null)

**And this is my job submit script:**

#!/bin/bash
#SBATCH --job-name=ipi_cp2k
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --mem-per-cpu=10GB
#SBATCH --time=168:00:00
#SBATCH --error=ipi_cp2k_job.%J.err
#SBATCH --output=ipi_cp2k_job.%J.out

# Test data used from https://github.com/i-pi/tutorials-schools/tree/main/tutorial-1/ex-2
# Run i-PI with UNIX socket, https://www.cp2k.org/howto:ipi
# UNIX socket requries for i-PI and cp2k to run on the same node

module purge
module load i-pi/py39/2.4
module load compiler/gcc/10 openmpi/4.1 cp2k/9.1

# print i-pi log
export PYTHONUNBUFFERED=1

# for no CUDA support set
export PSM2_CUDA=0
# for CUDA support set
# export PSM2_CUDA=1

HOST=$(hostname)

# UNIX socket requires only address modification
sed -i "s/address>[^<]*</address>$HOST</" input.xml
i-pi input.xml &> log.ipi &
sleep 20

# UNIX socket requires only address modification
sed -i "s/HOST.*/HOST $HOST/" cp2k.in
# This will start 20 cp2k jobs with --mem-per-cpu=10G on the same node where i-pi is running
# UNIX socket requries for i-pi and cp2k to run on the same node
mpirun `which cp2k` -i cp2k.in -o cp2k.out

**Comment by M0h4amad** [comment]
And this is the link to the tutorial:
https://github.com/i-pi/tutorials-schools/blob/main/tutorial-1/tutorial-1.ipynb

**Comment by ceriottm** [comment]
i-PI can use multithreading, but due to the GIL it ultimately runs in serial. this shouldn't be a problem up to ~ 100,000 atoms.
