### ISSUE TITLE
*** Proc    44 in run_driver: There are NaNs in your coords*** error while running aimd in fhiaims-ipi

### ISSUE THREAD

**Issue by shwetaresearchsite** [i-pi/i-pi#275]
What is the origin of this NaN error? When I perform MD on the periodic system, then only this type of error appears. What is the source of this error? 

input.xml:
`<simulation verbosity='low' mode='md'>
  <ffsocket name="FHI-aims"  mode="unix">
    <address>paramganga</address>
    <port>12345</port>
  </ffsocket>
  <total_steps>5000</total_steps>
  <output prefix='npt-simulations'>
    <properties stride='1'  flush='1' filename='dat'>[ step, time{picosecond}, conserved, potential{electronvolt}, volume, temperature{kelvin}, kinetic_md, pressure_md{bar}] </propertt
ies>
    <trajectory stride='10' format='xyz' cell_units='angstrom' filename='traj'> positions{angstrom} </trajectory>
    <checkpoint stride='100' overwrite='true' filename='chk'/>
  </output>
  <prng><seed>13111999</seed></prng>
  <system>
    <initialize nbeads='1'>
      <file mode='xyz' units='angstrom'> geometry.xyz </file>
      <cell mode="manual" units="angstrom">[13.97719061,     -0.00000000,      0.00038958,  -0.00000001,     10.57994070,     -0.00000000,  -0.70254865,     -0.00000001,      7.3018855
36]</cell>
      <velocities mode='thermal' units='kelvin'> 0 </velocities>
    </initialize>
    <forces>
      <force forcefield="FHI-aims"/>
    </forces>
    <ensemble>
      <pressure units='bar'> 1.0 </pressure>
      <temperature units='kelvin'> 0 </temperature>
    </ensemble>
    <motion mode='multi'>
      <motion mode='dynamics'>
        <dynamics mode='npt'>
          <barostat mode='isotropic'>
          <thermostat mode='svr'>
            <tau units='femtosecond'> 50 </tau>
          </thermostat>
          </barostat>
          <thermostat mode='svr'>
            <tau units='femtosecond'> 10 </tau>
          </thermostat>
          <timestep units='femtosecond'> 1.0 </timestep>
        </dynamics>
`

geometry.in:

`lattice_vector     13.97719061     -0.00000000      0.00038958
lattice_vector     -0.00000001     10.57994070     -0.00000000
lattice_vector     -0.70254865     -0.00000001      7.30188536
atom_frac       0.01377359      0.68701315      0.14091404 Ag
atom_frac       0.51377360      0.68701316      0.14091404 Ag
atom_frac       0.48622642      0.31298684      0.85908599 Ag
atom_frac       0.98622639      0.31298685      0.85908595 Ag
atom_frac       0.23622643      0.18701314      0.35908598 Ag
atom_frac       0.73622638      0.18701315      0.35908596 Ag
atom_frac       0.26377363      0.81298684      0.64091406 Ag
atom_frac       0.76377358      0.81298683      0.64091401 Ag
`

control.in:
`xc                                 pbesol
relativistic                       atomic_zora scalar
basis_threshold                    0.0005
k_grid                             1 2 2
spin                               none
compute_analytical_stress          .true.  
compute_forces                     .true.
use_pimd_wrapper                   UNIX:paramganga 12345
#postprocess_anyway                 .true.
`
geometry.xyz:
`8

Ag      0.093517117375812      7.268558385711064      1.028943531609646
Ag      7.082112562147718      7.268558491510472      1.029138321613542
Ag      6.192529646319634      3.311382198489528      6.273136837450810
Ag     13.181124560105861      3.311382304288935      6.273331335363708
Ag      3.049506466876763      1.978587927729938      2.622096689435852
Ag     10.038101087068206      1.978588033529345      2.622291333378666
Ag      3.236540988652727      8.601352550671248      4.679983752662936
Ag     10.225135629920628      8.601352444871841      4.680178177549190
`
Please help!

**Comment by mahrossi** [comment]
Hi Schweta, can you please send the inputs and outputs of the simulation as files? It looks like a problem in the unit cell definition, I think you have rows and columns switched.

**Comment by shwetaresearchsite** [comment]
Hi,
I am attaching files for another case where the same error is appearing. 
[npt.zip](https://github.com/i-pi/i-pi/files/12641341/npt.zip)

**Comment by mahrossi** [comment]
Ok, two things. First add pbc=False on this line:

 <ffsocket name="FHI-aims"  mode="unix" pbc="False">

and fix your definition of the cell in the i-PI input. As you can see (screenshot), you switched rows and columns. you should "transpose" the numbers in the i-PI input.

<img width="1367" alt="Screenshot 2023-09-17 at 00 20 11" src="https://github.com/i-pi/i-pi/assets/6743106/990c1dcc-f927-46cf-abf2-0dbca45efdb0">

Let me know if it solves it, I will close this.

**Comment by shwetaresearchsite** [comment]
Hi @mahrossi, as per your instructions I made the required changes but issue still remains same. I am attaching output/input files.
[npt.zip](https://github.com/i-pi/i-pi/files/12643172/npt.zip)

**Comment by mahrossi** [comment]
Hi Schweta, I cannot run your inputs at the moment, but I notice that you are running at 0 K. I guess this is intentional. However, I think there may be some issues with setting the temperature exactly to zero, given the error you have in the .err output. Could you try to put a very small number, instead of 0 (assuming you want to run at no temperature)? Something like 0.0001.

**Comment by shwetaresearchsite** [comment]
Thanks a lot @mahrossi ma'am!! I found there was also mistake in barostat section in input.xml. Now issue is resolved after "transposing" coords as well as putting T=0.0001K instead of 0K. I appreciate your time and help!!
