### ISSUE TITLE
Temperature not ramping up 

### ISSUE THREAD

**Issue by shwetaresearchsite** [i-pi/i-pi#276]
Hi,

When I am trying to ramp up the temp from 0 to 800K, I observe huge deviation in Temp, I tried varying tau parameter but the trend is same. Can anyone please help regarding T ramp up?

![t_ramp](https://github.com/i-pi/i-pi/assets/122591650/5b62a1b8-df35-4f5e-a0c0-6e508db2cf41)
[input.txt](https://github.com/i-pi/i-pi/files/12766107/input.txt)

Many thanks!

**Comment by ceriottm** [comment]
hello. you are running for 200fs a system that clearly starts very much out of equilibrium, and appears to have an intrinsic time scale of ~25fs. I'd say you are seeing just the normal effect of this, it'll take a few ps (at the very least) to equilibrate. 

Also, why would you like to run a ramp over a time scale of 1.6ps? If you're trying to equilibrate at 800K you're better off running at 800K from the start. Without knowing more about your system, it's hard to tell you more. 

Anyway, if you have similar "user" types of questions please use the [forum](https://groups.google.com/g/ipi-users), we try to keep gh as a communication channel for actual bugs.

**Comment by shwetaresearchsite** [comment]
Thanks a lot @ceriottm. 
I am sorry to post it here, I will use the forum from next time onwards.
I want to  ramp over a time scale of 1.6ps such that the temperature of the system rises slowly from 0 to 800 in such a way that it take 1K/2fs rise.  Since I am using optimized geometry of 0K , I didn't want to increase temp straightly to 800. So I am mentioning t_start and t_end from 0 to 800. Can you please help?

Thanks!
