### ISSUE TITLE
Missing information in I-Py documentation-- getting started.html #running-i-pi

### ISSUE THREAD

**Issue by ShubhangG** [i-pi/i-pi#296]
On the getting started with I-pi page, https://ipi-code.org/i-pi/getting-started.html#running-i-pi

under running the client code, for each client the main information about what modification needs to be made is missing from the website. Even when I click on view source that information is missing. Here is an example

> LAMMPS
> 
> To use LAMMPS as the client code using an internet domain socket on the host address “host_address” and on the port number “port” the following lines must be added to its input file:
> <<MISSING??>>
> If instead a unix domain socket is required then the following modification is necessary:
> <<MISSING??>>
> The rest of the input file should be the same as for a standard LAMMPS calculation, as explained at http://lammps.sandia.gov/index.html. Note that LAMMPS must be compiled with the yes-user-misc option to communicate with i-PI. More information from https://lammps.sandia.gov/doc/fix_ipi.html.

This scenario is for all the clients,where the important modification information is missing

**Comment by ceriottm** [comment]
Hi @ShubhangG thanks for reporting this. 
This is probably a side-effect of the automatic conversion we used to generate the .rst documentation starting from the old tex manual. It looks like all the `\begin{code}` sections got lost entirely. 

It'd be extremely useful if you could take a couple of hours to add them back, scanning `doc/latex/manual.tex` for code sections and adding them in the right place in a .rst file (ideally making sure the information in there is not obsolete, while you're at it). 

On my side, I'll add to #282 some documentation on the python driver, and on how to add a new PES on that front.

**Comment by ceriottm** [comment]
Hello @ShubhangG  and @mahrossi  - just reviving this: can you add these fixes to #302 ?

**Comment by ceriottm** [comment]
I believe this has been fixed in #302 . Closing it.
