### ISSUE TITLE
Sockets minimal working example

### ISSUE THREAD

**Issue by b-fg** [i-pi/i-pi#30]
Hi!

 I am very interested in the part of data exchange between Python and Fortran. Is there a minimal working example or test I can look into for this purpose? Just passing a 2D array from Fortran to Python and viceversa would be great.

I have gone through the code several times but the workflow of this process still is not clear to me. If this could be explained in this issue or a test example could be included in the package that would be very much appreciated.

Thanks,

Bernat

**Comment by ceriottm** [comment]
Hello. The driver.f90 code in i-pi/drivers is pretty minimalistic. From lines 325 on you get the main loop, and you can follow the back-and-forth communication between i-PI and the Fortran code.
In addition, the protocol is explained quite in detail in the manual.

**Comment by b-fg** [comment]
Thanks! I get everything I need for a minimal working example from the Python side is included in the sockets.py file?

**Comment by b-fg** [comment]
Got it after a while looking at the driver.f90 and sockets.py files. Thank you, this is very useful.
I will create a repo with a minimal working version of this and add it here for reference later.

**Comment by ceriottm** [comment]
Great you figured it out. Also keep in mind that @OndrejMarsalek was thinking of separating out the sockets infrastructure from the i-PI source so if you're thinking of something similar it may be good to coordinate with him.

**Comment by b-fg** [comment]
Thanks @ceriottm . I have created this [repo](https://github.com/b-fg/f2py-sockets) for this purpose (acknowledging i-pi). It's still a bit messy but I am working on it. At the moment I also want to implement it in Python 3.6 but I am struggling quite alot on the sockets.py inherited classes since the socket library changes significantly from 2.7 to 3.6. Do you think you could give me a hand? Should be fairly quick I reckon, but I am banging my head on the wall.

**Comment by b-fg** [comment]
Nevermind, managed to make it work (see latest [commit](https://github.com/b-fg/f2py-sockets/commit/7e20a1a911165aa0dcd206824e5498709bcb4994)). Something to keep in mind if you i-pi owners want to upgrade to 3.6...
