### ISSUE TITLE
Default NEB Spring Constant 

### ISSUE THREAD

**Issue by Montmorency** [i-pi/i-pi#31]
Greetings. Thanks very much for making this package available. I'm currently running NEB calculations through i-pi with the lm/tbe code as a driver. I noticed the NEB code default spring constant is:
/ipi/inputs/motion/neb.py
"default": [False, 1.0, 1.5, 0.5]

If I am correct this corresponds to ~50 eV/A. For comparison the ASE default is 0.1 eV/A. Am I reading the units correctly in this case? If so is there a reason for this choice of default? I suppose the choice is strongly system dependent. 

I am currently overriding this with:

```
        <spring>
            <kappa> 0.016 </kappa>
            <kappamax> 0.02 </kappamax>
            <kappamin> 0.01 </kappamin>
        </spring>

```
I suppose the issue is I want to make sure I am reading/resetting the units correctly, and that the default is set to a 'sensible' value.

thanks again.

**Comment by ceriottm** [comment]
Hi! All the units (unless otherwise specified) are in atomic units, so those defaults are indeed in Ha/bohr so yes those are huge. TBH we never used much the NEB implementation so you're a bit in uncharted territory. Try with those defaults, and feel free to get back to us if you find any problem. If these values work well, you can make a mini pull request to update them so that future users will have a reasonable value.

**Comment by Montmorency** [comment]
Thanks. I am currently testing and will issue a pull request to set kappa more on the order of ~1 eV/A. I was also wondering how to investigate the restart capabilities. (I've noticed the RESTART files when generated using the tbe driver are about ~5Gb but this may be a separate issue).

Currently, I am outputting the forces and positions of each step to prefix.force/prefix.pos files. When I resubmit the calculations I am concatenating all the position files into neb_restart.xyz and changing the ipi-input.xml to include:

`<file mode='xyz' units='angstrom'> neb_restart.xyz </file>`

Is there a more "ipi-thonic" way to do this? It would be nice to keep the old gradient information as well to restart the minimization.

**Comment by ceriottm** [comment]
So the RESTART file (which definitely shouldn't be 5GB, how large is your system?) is itself an input, so you can run i-pi  RESTART to restart a calculation.
If you want to edit parameters and only read the last positions, you should be able to do 
<initialization>
<file mode='chk'> RESTART </file>
</initialization>

**Comment by Montmorency** [comment]
Thanks very much. Yes the system is only 249 atoms. So I was somewhat surprised. Looking through the restart file I find it is storing this matrix for the lbfgs minimization:
            <invhessian_bfgs shape='(6723, 6723)'>
Eliminating storage of this would save a great deal of space.

**Comment by mahrossi** [comment]
Hello, any news here? From my tests some months ago, the NEB implementation was not working for the example we have in i-PI. If there are bugs to report, please do.
