### ISSUE TITLE
UNIX sockets in arbitrary file paths  (instead of `/tmp/ipi_*`)

### ISSUE THREAD

**Issue by svandenhaute** [i-pi/i-pi#320]
I'm in a situation where it is possible that a number of different i-pi simulations might be scheduled on the same node at the same time, each with a certain number of clients, and sometimes even within the same SLURM allocation. This creates a problem when using clients which connect via UNIX sockets, since the sockets will be created within the same `/tmp` folder, unless I manually change the addresses in the input file to be unique for each simulation (which is cumbersome). Without too much background knowledge on both the usage of UNIX sockets as well as i-pi, I'm naively tempted to just let each simulation create its own (temporary) directory upon starting i-pi, after which all of the sockets should just get created within that directory. This avoids collisions irrespective of the number of simulations or the number of clients, and does not require changing the input file.

Currently, sockets are forcibly named according to `/tmp/ipi_*`, which makes this approach tricky. What would be the easiest way to proceed? 
https://github.com/i-pi/i-pi/blob/e8601c4c501db7e9f43c5ae30f08446b3a52c7c9/ipi/interfaces/sockets.py#L608

**Comment by mahrossi** [comment]
Hi there - I would suggest you do change the unix socket names in each different input file if they are different runs. 

These types of manipulations can be done automatically with bash or python, so it shouldn't be too cumbersome. Maybe I miss something, but how would it be easier to use mktemp? wouldn't you then have to know the name of the directory that will be created for the input in the i-PI file? If you can create many such directories and know their names, presumably one could also just change the names in the input file with bash (or?).

**Comment by svandenhaute** [comment]
The problem is that it is not known in advance how many i-PI runs there will be and in which order or combination they will get executed, because the whole thing will be part of [psiflow](https://github.com/molmod/psiflow), a library for molecular simulation w/ ML potentials that we're developing. Execution of 'heavy' operations, such as DFT evaluations, ML potential training runs, and i-PI molecular dynamics runs get scheduled and distributed to compute resources by [Parsl](https://github.com/parsl/parsl), a parallel execution framework for Python. Users can define an arbitrary number of i-PI simulations and depending on their execution configuration and the availability of nodes and their dependencies, any combination of runs might be scheduled on the same node. As such, `mktemp` is I think the most elegant solution for now... 

In case you're interested: integration of i-PI into psiflow is happening [here](https://github.com/molmod/psiflow/tree/ipi/psiflow/sampling) ...

**Comment by ceriottm** [comment]
Hello @svandenhaute - using i-PI in an HPC environment is a bit of a pain, and I think we should do more to simplify the workflows. Can you look into #322 and see if it helps you achieve this goal without the `mktemp` workaround?

**Comment by svandenhaute** [comment]
I would in any case continue to use `mktemp` because it minimizes IO load in user directories (which are often in global data/scratch locations where IO is a concern) and moves it to local node storage if available.

Your fix looks good but unfortunately ASE also hardcoded `/tmp/ipi_` in their `SocketClient` [here](https://gitlab.com/ase/ase/-/blob/master/ase/calculators/socketio.py?ref_type=heads#L19), so I had to subclass it and override that behavior:

```
class SimpleSocketClient(SocketClient):
    def __init__(self, host='localhost', port=None,
                 unixsocket=None, timeout=None, log=None, comm=None):
        if comm is None:
            from ase.parallel import world
            comm = world

        self.comm = comm

        if self.comm.rank == 0:
            if unixsocket is not None:
                sock = socket.socket(socket.AF_UNIX)
                sock.connect(unixsocket)
            else:
                raise NotImplementedError
            sock.settimeout(timeout)
            self.host = host
            self.port = port
            self.unixsocket = unixsocket

            self.protocol = IPIProtocol(sock, txt=log)
            self.log = self.protocol.log
            self.closed = False

            self.bead_index = 0
            self.bead_initbytes = b''
            self.state = 'READY'

```

**Comment by ceriottm** [comment]
Yes, as I mentioned one would have to add an option for all other clients as well. Still, this is something that might simplify a bit the HPC scripts for i-PI so if having the possibility of setting the prefix as a CLI option rather than doing surgery on the xml input. Another thought - IDK how you implemented the parser but we recently merged some utility functions in #313 so maybe you can use those so also the maintenance is on our side.

**Comment by ceriottm** [comment]
Anyway, if you have any other "papercuts" issues we encourage you to report them, making the user experience on HPC better is one of our priorities, so we'll be very happy to help if we can.

**Comment by svandenhaute** [comment]
I've actually used the `read_output` utility function you wrote though I copied it for now since it's not yet released. Other than that, I wrote a checkpoint-to-ASE-atoms parser myself [here](https://github.com/molmod/psiflow/blob/9a26adbf13e7764611ec56b9bef6ac8d41f62ab1/psiflow/sampling/server.py#L16).
To be honest, the fact that Python has native support for xml makes input file manipulation relatively easy ([example](https://github.com/molmod/psiflow/blob/ipi/psiflow/sampling/sampling.py)), especially when compared to many other software packages in our field. This, together with the completely decoupled nature of i-PI server and client makes its use (at least via UNIX sockets) on HPC relatively straightforward? I'll be running both inside an Apptainer engine but that has a flag to allow inter-process communication so I expect no trouble there. Container compatibility was less relevant in the past when single-node runs for a PIMD code would not make much sense, but I think now it has the potential to make everyone's life easier.
When something new pops up, I'll open an issue! Thanks for the support.

**Comment by venkatkapil24** [comment]
Hey, @svandenhaute, does PR #322 help with ASE clients by default, or did you have to make changes to the ASE client too?

**Comment by svandenhaute** [comment]
Yeah the ASE client as a `/tmp/ipi_` baked in as well so that had to be overridden too. In particular, [this](https://gitlab.com/ase/ase/-/blob/master/ase/calculators/socketio.py?ref_type=heads#L434) line needed to change, which unfortunately forces me to subclass the entire thing and overwrite `__init__`. Not a big deal for me, but perhaps less-than-optimal.

**Comment by venkatkapil24** [comment]
So you mean your implementation works with an inhouse ASE and we may have to get in touch with them in the long run?

**Comment by svandenhaute** [comment]
Yes, indeed. Perhaps it’s better to just add a SocketClient for ASE inside i-PI? That way, users don’t get bothered with having to install the latest version of ASE from gitlab. ASE doesn’t have a frequent release cycle to say the least.

**Comment by venkatkapil24** [comment]
Yes that makes sense. Are you able to create a quick PR?

**Comment by ceriottm** [comment]
Question: it is now VERY easy to make a PES for `ipi-driver_py` when there is a compatible ASE-style calculator. Wouldn't that be an easier way to proceed? Anyway, I kind of like the idea of a from ipi import SocketClient, so :+1: for a PR doing that

**Comment by venkatkapil24** [comment]
Hi Michele, I think we can do both. Since the ASE SocketClient has a greater userbase it may make sense to prioritize doing that. I am happy to add it to the python one.

**Comment by svandenhaute** [comment]
I wasn't even aware of the whole `driver` module in this repository. I avoid ASE code as much as I can so I'd actually much prefer your suggestion. Also in that case your PR covers everything already since you also changed `driver.py`, and there's no need to change things.

**Comment by ceriottm** [comment]
Yeah but I like the idea of providing a Python hook for the socket interface modeled after the ASE one, so people who don't want to use a CLI tool can also do that. Should be easy enough, maybe you and Venkat can add it here?

**Comment by svandenhaute** [comment]
wait am I missing something or is it just something like this (to do it non-CLI with the current codebase):

```
from ipi._driver import run_driver


driver = ASEDriver()
driver.ase_calculator = MyASECalculator()

run_driver(driver=driver, **kwargs)
```

**Comment by svandenhaute** [comment]
Sounds reasonable! `ipi.interfaces` is where I as a new user would go looking for something like this... 

In the meantime, I have switched to the `ASEDriver` approach for psiflow purposes [here](https://github.com/molmod/psiflow/blob/ipi/psiflow/tools/client.py#L52) (just FYI)

**Comment by venkatkapil24** [comment]
Just continuing the discussion here. 

@ceriottm I am just thinking if PR #322 is the most user-friendly tweak. If this is to be extended to other codes they will require a separate prefix keyword in the client input.  How about (I can make the change) we instead check if the socket string contains a '/'. If it does, we use the path to create the socket. If it doesn't, we use '/tmp/ipi_' as the prefix. 

This may be better as the way i-pi is called in other codes will remain the same. The user can change the socket address to the full path without having to specify a new keyword. @svandenhaute does this sound more convenient?

**Comment by ceriottm** [comment]
> @ceriottm I am just thinking if PR #322 is the most user-friendly tweak. If this is to be extended to other codes they will require a separate prefix keyword in the client input. How about (I can make the change) we instead check if the socket string contains a '/'. If it does, we use the path to create the socket. If it doesn't, we use '/tmp/ipi_' as the prefix.

Also, the client codes will have to be changed also in this scenario.

**Comment by svandenhaute** [comment]
If the original idea was to use standard prefixes to simplify submission scripts, perhaps it's best to use env variables?
Something like this:

```bash
# if IPI_SOCKET_PREFIX is not defined, i-pi server defines it, e.g. to /tmp/ipi_
i-pi input.xml &

python my_client.py &  # reads from the env variable IPI_SOCKET_PREFIX; returns error if not defined
```
Not a big fan of checking for specific characters in a certain string -- sounds prone to bugs somehow? Default software behavior, especially in terms of location on the file system, is typically the job of environment variables I think, so for me this approach would feel most intuitive.

For my use case, I would then have something like this:
```bash
export IPI_SOCKET_PREFIX=$(pwd)
i-pi input.xml &
python my_client.py &
```

The main `i-pi` script would check for the existence of `IPI_SOCKET_PREFIX` maybe somewhere [here](https://github.com/i-pi/i-pi/blob/8fdf525ec189944ff66a4bf545af45f9bfca340e/bin/i-pi#L64), and set it to the default value of `/tmp/ipi_` if it has not yet been set by the user.
Requires changing this PR to remove all default prefix stuff, and just read from `os.env['IPI_SOCKET_PREFIX']` in `run_driver`.

**Comment by ceriottm** [comment]
> don't have enough experience with `inet` to understand whether this also covers that case though I think it does, perhaps with the extension that there needs to be a default port env variable or something.

For inet the natural thing to do is make the address the "prefix" part, and then let input-level-defined ports differentiate between different sockets within one input
