### ISSUE TITLE
bug in ipi/engine/motion/instanton.py  class Springmapper(object): __call__(self, x, ret=True, new_disc=True) function

### ISSUE THREAD

**Issue by Phyzch** [i-pi/i-pi#321]
1. Report bug in __call__ function in Springmapper class.

I think the code use the normal mode gq_k computes the gradient "g" but forgets to compute the energy e.

add code  "e = 0.5 * np.sum( np.power(self.omegak,2)[:, np.newaxis] * (self.dbeads.m3 * np.power(gq_k, 2)) )" to compute energy of spring terms.

2. I also have question about:
evaluate(self) function in PesMapper class

The code "e = e * (self.coef[1:] + self.coef[:-1]) / 2" will make energy e has shape [nbeads, nbeads], which is problematic.

The code should be : "e = e * (self.coef[1:,0] + self.coef[:-1,0]) / 2 ". This way e has shape [nbeads], which represent the physical potential term for each bead. 

3.  in Mapper class, initialize() func,   "e = e1 + e2" should be e = np.sum(e1) + np.sum(e2), because e1 is a vector (potential energy for each bead) but e2 is a number (potential energy for all spring terms).

The same idea applies to the __call__(self,x, mode="all", apply_fix=True, new_disc=True, ret=True) function in the Mapper class :  e = e1 + e2 should be e = np.sum(e1) + np.sum(e2).

I am not quite sure about the meaning of the bool variable "self.esum", I think energy "e" should be defined as the total energy of all beads.

**Comment by litman90** [comment]
Thanks for reporting the bug. I will have a look into it in the following days (and reply to the rest of your questions as well).

**Comment by Phyzch** [comment]
Thanks. I also have two more bugs to report about instanton module:
1. in /ipi/drivers/py/pes/doublewell.py: line 49 "arglist = self.args.split(",")". 
This is a bug. 
should change this line to "arglist = self.args"

This is because in "/ipi/drivers/py/pes/dummy.py", line 14, we already convert self.args into list : "self.args = args.split(",")"

If we "run run.sh" example in "/examples/features/ring_polymer_instanton/rates_1D_double_well/", we can see error message from the code "Invalid arguments for the PES".

Also suggest to change line 36 in "doublewell.py", which is "super(DoubleWell_driver, self).__init__(args)" to 
"super(DoubleWell_driver, self).__init__(args, error_msg = self.error_msg)"
otherwise, the error message that Doublewell_driver will report is the error message of the Dummy_driver, which is not very helpful.

2. I also think there is a small bugs in "tools/py/Instanton_postproc.py", line 396 - 400:
"outfile = open("freq.dat", "w")
    aux = np.zeros(nzeros)
    dd = np.concatenate((aux, d))
    np.savetxt(outfile, dd.reshape(1, dd.size))
    outfile.close()"

Here, the data in "freq.dat" should be frequency. If we intend to store frequency in atomic units, then it should be:
"dd = np.sqrt(dd)", as "d" we compute here is eigenvalue of hessian, which is square of frequency. 
Of course, if in the initial design, the output result in "freq.dat" is eigenvalue of hessian, then we don't have to do anything. But then the file name "freq.dat" is misleading.

Please let me know what you think. Thanks.

Best,
Chenghao.

**Comment by Phyzch** [comment]
Hi, there,
     Sorry to send the message here again. 
     I think there is another small bug in /utils/mintools.py in nichols(f0,d,,dynmax, m3, big_step, mode=1) function.
     At line 1585, the code is "alpha = (d[1] - d[0]) / d[1]"
     If I understand the paper correctly, the code should be "alpha = (d[1] - d[0]) / d[0]".

     Please let me know what you think. Thanks.

**Comment by mahrossi** [comment]
> Hi, there, Sorry to send the message here again. I think there is another small bug in /utils/mintools.py in nichols(f0,d,,dynmax, m3, big_step, mode=1) function. At line 1585, the code is "alpha = (d[1] - d[0]) / d[1]" If I understand the paper correctly, the code should be "alpha = (d[1] - d[0]) / d[0]".
> 
> Please let me know what you think. Thanks.

Hey, I will let Yair comment on the first questions bec
ause I think he is onto it, but here I am pretty sure line 1585 is correct. d[0] is the first eigenvalue (corresponding to h1 in Nichols original paper) and d[1] is the second eigenvalue (corresponding to h2 in Nichols original paper). I print screen the original paper relevant section below, see point (ii) -- that is what is implemented for alpha indeed.

<img width="535" alt="Screenshot 2024-04-05 at 10 31 23" src="https://github.com/i-pi/i-pi/assets/6743106/9be7efc4-1028-4529-993d-fcfac686bece">

**Comment by Phyzch** [comment]
Hi, thanks for the reply. 

I see, I think line what I really mean is line 1595 : d[1] <0 and d[1] < d[0]/2 case. 
The right one in my idea is "alpha = (d[0] - d[1]) / d[0]" but the code is "alpha = (d[0] - d[1]) / d[1]". 
Interestingly, this case is not mentioned in Nichols' paper. 

I don't think this will make much difference as the current code works great.

**Comment by litman90** [comment]
Again thanks Chenghao for reaching out. I reply in chronological order

Regarding the first message. 
1 ) You are right, this term has been accidentally commented
2 ,3 ) you are also right, there is an inconsistency in the dimensions.

I am creating a PR that will fix this.
Note, however, that the optimized geometry is not affected but this bugs since the actual value of the energy is not used
to predict the new step nor to check the convergence. For the latter we check, changes in energy, maximum force component and maximum step component.

Regarding the second message:

1) You are right, this has been broken by this commit 0e9284991cf6c03da8e9caa4d08b28e1b4480581
I've just fixed it and it will included in the PR.

2) 'the freq.dat' file was a debugging file that should be there. Thanks for spotting it. (but yes, frequencies should be computed as done in line 380 in that file)

Regarding the second message:
1) MR already replied. You can have a look at Jeremy Richardson's thesis.  https://www.repository.cam.ac.uk/items/9a42ddbf-f734-4c49-be1d-28e9f0994c03
2,3) thanks

**Comment by litman90** [comment]
I am closing the issue since the PR has already been created. 
Feel free to open it or create a new issue if you find it appropriate.

Thanks again Chenghao for taking the time to report these bugs.

**Comment by Phyzch** [comment]
Hi, Thanks Yair for fixing the errors. I think I found another bug in the instanton.py module:
In LanczosOptimizer class, step() function:
Line 1751 - 1756:
        if banded:
            h_up_band[-1, :] += -np.ones(h_up_band.shape[1]) * lamb
            d_x = invmul_banded(h_up_band, f)
        else:
            h_test = alpha * (h_test - np.eye(h_test.shape[0]) * lamb)
            d_x = np.linalg.solve(h_test, f)

I don't think this formula treats variable "alpha" correctly. The right code should be :
         if banded:
                h_up_band[-1,:] + = -np.ones(h_up_band.shape[1]) * lamb
                d_x = invmul_banded(h_up_band, f)*  alpha
          else:
                 h_test = h_test - np.eye(h_test.shape[0]) * lamb
                 d_x = np.linalg.solve(h_test, f) * alpha

According to eq.(5) in Nichols' paper (J. Chem. Phys. 92, 340–346 (1990)). alpha is the step scale factor, thereforfe, the correct matrix form for this equation is : (H - lamb * I) X = alpha * f  (where f is the force vector). 
The code in the current repo, in the banded case, will forget to multiply alpha, in full matrix form case, will divide the d_x by alpha instead of multiplying it by alpha.

Let me know what you think. Thanks.
