### ISSUE TITLE
Bug in ipi/engine/instanton.py: LanczosOptimizer step() function, line 1751 -1756

### ISSUE THREAD

**Issue by Phyzch** [i-pi/i-pi#325]
Hi, Thanks Yair for fixing errors. I think I found another bug in the instanton.py module:
In LanczosOptimizer class, step() function:
Line 1751 - 1756:
        if banded:
            h_up_band[-1, :] += -np.ones(h_up_band.shape[1]) * lamb
            d_x = invmul_banded(h_up_band, f)
        else:
            h_test = alpha * (h_test - np.eye(h_test.shape[0]) * lamb)
            d_x = np.linalg.solve(h_test, f)

I don't think this formula treats variable "alpha" correctly. The right code should be :
         if banded:
                h_up_band[-1,:] + = -np.ones(h_up_band.shape[1]) * lamb
                d_x = invmul_banded(h_up_band, f)*  alpha
          else:
                 h_test = h_test - np.eye(h_test.shape[0]) * lamb
                 d_x = np.linalg.solve(h_test, f) * alpha

According to eq.(5) in Nichols' paper (J. Chem. Phys. 92, 340–346 (1990)). alpha is the step scale factor, thereforfe, the correct matrix form for this equation is : (H - lamb * I) X = alpha * f  (where f is the force vector). 

The code in the current repo, (1) in the banded case, will forget to multiply alpha
(2) in full matrix form case, will divide the d_x by alpha instead of multiplying it by alpha.

Let me know what you think. Thanks.

**Comment by litman90** [comment]
Thanks, Chenghao again for your input. This has been a hectic week for me. I will have a look at this and finish the PR #324 early next week.

**Comment by litman90** [comment]
Thanks, Chengho. I agree with both suggestions, I have fixed it and it will be merged as part of PR #324. However, let me add, that I would advise using Lanczos only when one already has a good initial guess obtained by a previous instanton calculation with a smaller number of beads. In these cases, one falls into the case where alpha=1. 

Thanks again, I consider this issue to be solved/handled so I will close. Feel free to open it, if you consider it necessary.
