### ISSUE TITLE
`remdsort` does not appear to be compatible with a multi smotion `remd` / `metad`

### ISSUE THREAD

**Issue by svandenhaute** [i-pi/i-pi#332]
The convenience function `remdsort` appears to check for a `mode` attribute for each of the elements in `smotion`. However, when it is called on the following input file which has both replica exchange and metadynamics as smotions, it throws an error at the following line 

https://github.com/i-pi/i-pi/blob/75cdc7b47949b5e04f327df498bd9d3c3d36f488/tools/py/remdsort.py#L59

saying `AttributeError: 'MetaDyn' object has no attribute 'mode'`. The smotion part of my input file looks like this:

```
  <smotion mode="multi">
    <smotion mode="remd">
      <remd>
        <stride>5</stride>
        <krescale>True</krescale>
        <swapfile>replica_exchange</swapfile>
      </remd>
    </smotion>
    <smotion mode="metad">
      <metad>
        <metaff> [ metad0 metad1 ] </metaff>
      </metad>
    </smotion>
  </smotion>
```

**Comment by ceriottm** [comment]
Hi @svandenhaute I had missed this. It's great that you find and report all these bugs, I just wanted to say that if you have the bandwidth to also open a PR to fix them it'd be fantastic. In this case, it's probably a one-liner.

**Comment by svandenhaute** [comment]
I am pretty saturated with work overall so I'm trying not to get distracted in small bugs in other software too much. In a few months, I should have some time to open PRs. i-PI has been great for our research so it makes sense for us to contribute in terms of bug reporting and fixing. For now, they're mostly "FYI" issues -- most of them can be circumvented so they're not really critical.
