### ISSUE TITLE
i-PI system template matching substitutes substrings

### ISSUE THREAD

**Issue by svandenhaute** [i-pi/i-pi#343]
Consider the following input file:

```
<simulation verbosity="high">
  <ffsocket mode="unix" name="PlumedHamiltonian1" pbc="False">
    <timeout>10.0</timeout>
    <exit_on_disconnect> TRUE </exit_on_disconnect>
    <address>plumedhamiltonian1</address>
  </ffsocket>
  <ffsocket mode="unix" name="PlumedHamiltonian10" pbc="False">
    <timeout>10.0</timeout>
    <exit_on_disconnect> TRUE </exit_on_disconnect>
    <address>plumedhamiltonian10</address>
  </ffsocket>
  <output prefix="output">
    <checkpoint filename="checkpoint" stride="250" overwrite="True" />
  </output>
  <system_template>
    <labels>[ INDEX, TEMP, PLUMEDHAMILTONIAN1, PLUMEDHAMILTONIAN10 ]</labels>
    <instance>[ 98, 1000.0, 1.0, 0.0, ]</instance>
    <instance>[ 98, 1000.0, 0.0, 1.0, ]</instance>
    <template>
      <system prefix="walker-INDEX">
        <initialize nbeads="1">
          <file mode="ase" cell_units="angstrom"> start_INDEX.xyz </file>
          <velocities mode="thermal" units="kelvin"> TEMP </velocities>
        </initialize>
        <motion mode="dynamics">
          <dynamics mode="nvt">
            <timestep units="femtosecond">0.5</timestep>
            <thermostat mode="langevin">
              <tau units="femtosecond">100</tau>
            </thermostat>
          </dynamics>
          <fixcom> True </fixcom>
        </motion>
        <ensemble>
          <temperature units="kelvin">TEMP</temperature>
        </ensemble>
        <forces>
          <force forcefield="PlumedHamiltonian1" weight="PLUMEDHAMILTONIAN1" />
          <force forcefield="PlumedHamiltonian10" weight="PLUMEDHAMILTONIAN10" />
        </forces>
      </system>
    </template>
  </system_template>
  <smotion mode="remd">
    <remd>
      <stride>1000</stride>
      <krescale>True</krescale>
      <swapfile>replica_exchange</swapfile>
    </remd>
  </smotion>
  <total_steps> 5000 </total_steps>
  <prng>
    <seed> 12345 </seed>
  </prng>
</simulation>
```
The intended substitution would be that `PLUMEDHAMILTONIAN1`  would get matched only to `weight="PLUMEDHAMILTONIAN1"`, but in reality, due to [this line](https://github.com/i-pi/i-pi/blob/453fa33de9867aa2d18f62f9039ea148ca038249/ipi/inputs/system.py#L92), he would also blindly substitute it into the second force since it just replaces any occurrence. Woulnd't it make more sense to first find all occurrences of the template parameter, but filter out those for which the enclosing double quotes include other characters, such that when only a substring is matched, it actually ignores this? 
Alternatively, as a user, I need to guarantee there is absolutely no chance of substring matching. While that's possible, it seems like something which would be safer to fix on the i-PI side ...

**Comment by ceriottm** [comment]
A simple patch would be to sort labels in order of decreasing length and start substituting from the longest.

**Comment by svandenhaute** [comment]
What about this:

```
import re

# Input string
input_string = 'This is "some_string" and this is not "some_string1".'

# Pattern to match "some_string" exactly
pattern = r'"some_string"'

# Replace "some_string" with "some_value"
result = re.sub(pattern, '"some_value"', input_string)

print(result)

```

Safer when people are accidentally trying to replace a parameter named some_string in a system template which only has some_string1. Your solution would I think not throw an error in those cases.
I can make a PR for this if this is fine.

**Comment by svandenhaute** [comment]
The regexp approach is not the best. It needs disallow all matches which are surrounded by letters/numbers/underscore, but ignore everything else. The regexp string chatgpt generated for me became a bit long and in any case hard to read so I think just sorting before replacing is fine.
