### ISSUE TITLE
whether the i-pi support openmm?

### ISSUE THREAD

**Issue by XiaoTongDeng** [i-pi/i-pi#345]
Hello, I would like to ask if I-pi supports openmm. The situation is that I have a potential model based on machine learning that needs to be used in conjunction with openmm, but I am confused about whether I-pi supports openmm

**Comment by mahrossi** [comment]
Hello, we are not aware of an explicit interface of i-PI with openmm. Note that if openmm is interfaced with ASE or with LAMMPS, then you can use a double interface and access your potential any ways.

**Comment by ceriottm** [comment]
Looks like there's plenty of ASE interfaces for openMM https://narupa.readthedocs.io/en/latest/python/narupa.ase.openmm.calculator.html which you can then interface with i-PI. Alternatively, it should be very easy to set up a PES file that calls openMM through the python driver, see `drivers/py/pes` for examples. If you go the second way, feel free to contribute what you do.
