### ISSUE TITLE
Examples Metadynamics broken

### ISSUE THREAD

**Issue by litman90** [i-pi/i-pi#364]
The example features/metadynamics/pimd_metadynamics_zundel seems broken. 
I can make i-pi run if I replace the tag 'plumedextras' with 'plumed_extras', however, the 'data.doo_0' file, which is supposed to get the 'doo' values, is printing only zeros. The 'plumed/COLVAR' values look reasonable.

I tested with nbeads=1, and the problem remains.
Tagging @ceriottm, who I think implemented this communication of extra strings between i-pi and plumed.

**Comment by ceriottm** [comment]
I'm looking into this. Works fine on my system, are you using a recent version of plumed? There was a bug in the initialization that was fixed relatively recently.

**Comment by litman90** [comment]
I am using 2.9.1

**Comment by litman90** [comment]
with version 2.10.0-dev (commit 12 Aug,  a44c5cd2dd00aa91ff8c7e189efaa998ebdb8792) everything works fine.
