### ISSUE TITLE
Question about use i-PI with jaxmd

### ISSUE THREAD

**Issue by Chenghao-Wu** [i-pi/i-pi#371]
Dear i-pi Developers,

I am trying to use i-PI with jaxmd to include some jax-based machine learning force-fields.

May I ask if there is any example or plan to integrate i-pi with jax-md? if not, is there any suggestion where I could start with?

Thank you very much for your time!

Best,
Zhenghao

**Comment by ceriottm** [comment]
I don't see a practical path to integrate jax-md with i-PI, nor the purpose, as both are meant to be MD engines. you can definitely implement torch and jax energy engines with i-PI if what you're trying to achieve is to use a MLIP written in jax to perform path integral MD. easiest way would then be through a new PES file in `drivers/py/pes`.

**Comment by Chenghao-Wu** [comment]
Hi Michele,  thank you very much for your kind suggestion! It is indeed no need to use jax-md for the PIMD. The i-pi python driver works very well! Thank you again for your help!

**Comment by ceriottm** [comment]
Excellent, good to know.
