### ISSUE TITLE
Bug report: instools.py: get_imvector(h,m3)

### ISSUE THREAD

**Issue by Phyzch** [i-pi/i-pi#379]
Hi, there,
    I find there is a bug in instools.py : get_imvector(h,m3) which is used to extend the initial instanton path around the transition state. 

In line 212, the code is : imv = w[:, 0] * (m3[:] ** 0.5) 

I think this is wrong, because w[:,0] is the eigenvector of mass scaled coordinate \sqrt{m} q, therefore, to get the eigenvector of the coordinate q, we should have:  
imv = w[:,0] / (m3[:] ** 0.5).

I test the code use my own example, where the code fails to give the correct unstable mode. After I correct it, it gives the right unstable mode. Please let me know what you think. Thank you.

Best,
Chenghao Zhang.

**Comment by litman90** [comment]
Hi Chenghao,
thanks for reaching out.
I will check this next week and let you know.
Best,
Yair

**Comment by litman90** [comment]
Hi Chenghao,
I apologize for the slow response. I hade a closer look at your comment and your observation is right. Could you create a pull request with the bugfix?
Thanks for your contribution and for reaching out
Best,
yair

**Comment by litman90** [comment]
merged. Thanks!
