### ISSUE TITLE
i-pi compatibility with on-the-fly machine learning force fields in VASP

### ISSUE THREAD

**Issue by wxwth** [i-pi/i-pi#387]
Dear i-pi developers,

I am writing to inquire whether i-pi supports calculation using VASP’s on-the-fly machine learning force fields. My question arises due to differences in certain labels within the OUTCAR file when using MLFF, compared to those at the first-principles level, such as:
(1) “**ML FORCE on cell =-STRESS**” vs. “**FORCE on cell =-STRESS**”
(2) “**TOTAL-FORCE (eV/Angst) (ML)**” vs. “**TOTAL-FORCE (eV/Angst)**”
(3) “**ML FREE ENERGIE OF THE ION-ELECTRON SYSTEM**” vs. “**FREE ENERGIE OF THE ION-ELECTRON SYSTEM (eV)**”
(4) “**free  energy ML TOTEN**” vs. “**free  energy   TOTEN**”
(5) “**ML energy  without entropy**” vs. “**energy  without entropy**”
(6) “**ML energy(sigma->0)**” vs. “**energy(sigma->0)**”

I am wondering whether these differences might impede data transmission in i-pi. If so, it may be necessary to modify the existing VASP patches to enhance the compatibility of i-pi. Thank you for your time and consideration.

Sincerely,
Xu

**Comment by mahrossi** [comment]
Dea Xu, i-PI does not parse outputs but rather communicates directly through sockets. As long as VASP assigns energies and forces (and stresses) to the usual internal variables there should be no issue - however, I don't know that it does when it is running the MLFF or that the patches also wrap around tha VASP-MLFF operating mode. This would have to be checked on the VASP side.

**Comment by mahrossi** [comment]
I will close this issue as I do not think this is an i-PI issue. If more VASP support is needed we are happy to talk to the VASP delvelopers.
