### ISSUE TITLE
[general discussion] HDF5 trajectories

### ISSUE THREAD

**Issue by azag0** [i-pi/i-pi#4]
Hello. We were talking with Mariana about storing trajectories in HDF5 instead of plain text. I really like your code, I think I can learn from it, and actually implementing some new stuff is a good and useful way to learn. Could you point me to files/classes which I should go through to be able to reasonably do this? I've only briefly wandered around the code/general architecture so far.

**Comment by OndrejMarsalek** [comment]
We now have some infrastructure in (thanks, @tomspur), so to get back to the point of compressed trajectories, I would suggest that we use a library that is easily accessible from Python. MDTraj (http://mdtraj.org/) mentioned above looks like an interesting option, as it can read/write multiple common (potentially compressed) formats as well as its own HDF5-based format. Making it optional is easy with the flexibility of Python imports.

**Comment by OndrejMarsalek** [comment]
I just realized I was brought here by a cross-repository link. That infrastructure is in the development repository, my point is the same, though.
