### ISSUE TITLE
Two random seeds being printed out : edit: Four random seeds being printed out

### ISSUE THREAD

**Issue by venkatkapil24** [i-pi/i-pi#401]
I ran the mace example in clients I got the following output, which prints out two random number seeds:

<ipi.inputs.motion.dynamics.InputDynamics object at 0x110813c10>
 # Initializing system object 
@ RANDOM SEED: The seed used in this calculation was 31415
 # Initializing simulation object 
 # Initializer (stage 1) parsing positions object.
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Interpreting input with dimension length, units ase and cell units ase
 # Initializer (stage 1) parsing masses object.
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Interpreting input with dimension length, units ase and cell units ase
 # Initializer (stage 1) parsing labels object.
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Interpreting input with dimension length, units ase and cell units ase
 # Initializer (stage 1) parsing cell object.
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Interpreting input with dimension length, units ase and cell units ase
 # Initializing from file init.xyz. Dimension: length, units: automatic, cell_units: automatic
 # Interpreting input with dimension length, units ase and cell units ase
 # Initializer (stage 1) parsing velocities object.
 # Resampling velocities at temperature 300.0 kelvin
 # Binding the forces 
 # Initializer (stage 2) parsing positions object.
 # Initializer (stage 2) parsing masses object.
 # Initializer (stage 2) parsing labels object.
 # Initializer (stage 2) parsing cell object.
 # Initializer (stage 2) parsing velocities object.
Created unix socket with address driver
 @ForceField: Starting the polling thread main loop.
@ RANDOM SEED: The seed used in this calculation was 1731493452785
@ RANDOM SEED: The seed used in this calculation was 1731493452795
 # i-PI loaded input file:  input.xml

**Comment by venkatkapil24** [comment]
To add some more information: the seed is printed out three times. The first one corresponds to the one specified in the input file, while the other two aren't. The first one is triggered in `input/prng.py` line 101 in fetch. I haven't figured out where the second and third are triggered.

**Comment by venkatkapil24** [comment]
The second one is triggered in the simulation.py  

        self.chk = eoutputs.CheckpointOutput("RESTART", 1, True, 0)
        **self.chk.bind(self)**
        
The third one also in the simulation.py in dco.bind

       self.outputs = []
        for o in self.outtemplate:
            dco = deepcopy(o)  # avoids overwriting the actual filename
            if self.outtemplate.prefix != "":
                dco.filename = self.outtemplate.prefix + "." + o.filename
            if (
                type(dco) is eoutputs.CheckpointOutput
            ):  # checkpoints are output per simulation
                **dco.bind(self)**
                dpipe(
                    dco._step, o._step
                )  # makes sure that the checkpoint step is updated also in the template
                self.outputs.append(dco)

**Comment by venkatkapil24** [comment]
So both are tiggered here 


    def bind(self, simul):
        """Binds output proxy to simulation object.

        Args:
           simul: A simulation object to be bound.
        """

        self.simul = simul
        import ipi.inputs.simulation as isimulation

        *self.status = isimulation.InputSimulation()*
        self.status.store(simul)

**Comment by venkatkapil24** [comment]
It prints out four random seeds. The first one is the first line of the i-pi log.

**Comment by mahrossi** [comment]
I am addressing this, it prints out I think as many random seeds as threads.

**Comment by mahrossi** [comment]
Fixed in #405 -- git pulled a trick at me and I am recommiting a previous commit as well - blergh. anyways.
