### ISSUE TITLE
Column major vs row major -- driver.f90

### ISSUE THREAD

**Issue by zerothi** [i-pi/i-pi#44]
Is there a reason why you would do:

```fortran
real :: xyz(:,3)
```
in your driver program? It looks like a mistake when going from C to F?

For fortran standard one would *always* do:
```fortran
real :: xyz(3,:)
```

**Comment by ceriottm** [comment]
driver.x is not really designed to be uberefficient, so we just stuck with row-major since this is how the data is passed from the python side. trust me there are much more pressing issues to worry about than cache misses. cheers
