### ISSUE TITLE
Is there a branch with Python 3 support?

### ISSUE THREAD

**Issue by afonari** [i-pi/i-pi#52]
Hi, %subj.

I would like to contribute to the port to Python 3.

Sasha

**Comment by ceriottm** [comment]
You're very much welcome. We're waiting end of october to merge a few open PR, then we will create wip/py3 branch and do the porting. Future PR will have to be made to that branch, untill it's merged to master.

**Comment by afonari** [comment]
Sounds good. Meanwhile I suggest hooking up a travis CI that will run pytest both for python 2 and python 3. I can submit a PR.

**Comment by ceriottm** [comment]
Can you use circleCI? I think there's already a configuration, that however
currently runs just a couple of minimal unit tests.

**Comment by mahrossi** [comment]
I will close this issue.
