### ISSUE TITLE
i-pi & CP2K working on multiple beads 

### ISSUE THREAD

**Issue by igirotto** [i-pi/i-pi#55]
At the ICTP we aim to make a PRACE project proposal based on using i-pi together with CP2K, where i-pi computes path integrals among multiple beads running in parallel. The most efficient way it is normally to place one bead per each allocated node having i-pi running in background on one of the nodes. The main problem is that sometime i-pi excludes the nodes from the client lists. It seems like the problem can be solved by setting the timeout parameter of the .xml input file to either 0 or a big number, for example: 

[...]
    \<forces\>
       \<socket mode='inet' pbc='False'\>
          \<address\>r162c02s01\</address\> \<slots\>5\</slots\> \<port\>21153\</port\> \<latency\>10\</latency\> \<timeout\>5000\</timeout\>
       \</socket\>
    \</forces\>
[...]  

What I understand is that in both cases i-pi detects a client is not responding and it will continue to schedule the calculation on the remain nodes/clients. However, this is also inefficient as you would normally continue to run on the remain nodes while paying for all initially allocated resources. I guess the ideal would be that if some of the client doe not respond for a while the simulation terminates as a restart is needed at that stage. 

I wanted to ask if you confirm the way we are understating this and if you have any suggestions about how to end the simulation when a CP2K client is not longer (i.e., for several minutes) responding.  

Ivan Girotto (ICTP)

**Comment by mahrossi** [comment]
Dear Ivan,

I think I don't understand the problem very well. What do you mean by "i-PI excludes the nodes from the client list"? Could you be more specific about the symptom of the problem you are seeing?

**Comment by igirotto** [comment]
Dear Mariana, 

thanks for your prompt reply. It is really appreciated.

You understood correctly. We want to avoid i-pi to keep working on the surviving instances. Indeed, when it happens the number of instances per node unbalanced while we keep also accounting for all the nodes were initially allocated. Therefore, the fault tolerance is not efficient in that case. 

The symptom is as follows:

nb-21-195:ICTP_TMP igirotto$ grep Removing log_local.dat -A 2 -B 2 
 @SOCKET: Assigning [  any] request id    3 to client with last-id    2 (  3/  4 : ('10.20.2.6', 38901))
 @SOCKET: Assigning [  any] request id    4 to client with last-id    6 (  2/  4 : ('10.20.2.7', 47602))
 !W!  @SOCKET:   Client ('10.20.2.16', 49326) died or got unresponsive(C). Removing from the list.
 @SOCKET: Assigning [ free] request id    0 to client with last-id    3 (  2/  3 : ('10.20.2.6', 38901))
 # Average timings at MD step    3439. t/step: 5.34464e+02 [p: 5.33307e+02  q: 8.38041e-04  t: 1.89681e-02]

Ivan

**Comment by venkatkapil24** [comment]
Hey Ivan, 

Can you also share the i-pi, cp2k input along with the submission script that you are using ? 

Best,
Venkat

**Comment by ceriottm** [comment]
What is the time/step *before* the client is removed, and what is it after
the first step when it is removed?
Best
Michele

**Comment by unmesh1993** [comment]
Hello everyone,
I ran the calculations regarding the issue Ivan raised. Attaching the i-pi input file (input.xml), cp2k.in (in.cp2k), job script (job_7.sh) and the log file (log) it generated. 

The removal of client  by i-pi can be found out in the line number '26361' of the log file which prompted us to make the query. However, on further inspection of the log file,  we observe  an error  related to I/O from the client side(cp2k) (at line numbers '26325-26327' ). 

Is it something that can be redressed? 
Thanks 
Unmesh



[send.zip](https://github.com/i-pi/i-pi/files/3716973/send.zip)

**Comment by ceriottm** [comment]
OK I see. We always saw this "fault tolerance" as a feature, but I see how
it kills the efficiency of the calculation in cases in which you run with
same number of images as nodes. I think I see how I could implement an
option to let i-pi terminate gently when a client dies - will give it a go
later .

**Comment by igirotto** [comment]
@ceriottm thanks a lot

**Comment by mahrossi** [comment]
Alternatively, you can make your submission script do it for you. You can
devise a way to make your script "touch EXIT" in the directory if a client
dies. That is a "hack" though, in a way. However, because this problem is
very specific to the way you are running, this could be a good way to go.

**Comment by ceriottm** [comment]
Actually, the ideal thing would be to determine if a cp2k job dies and re-launch it. 
Anyway, I'm about to open a pull request that implements an option to die upon client disconnect. Test if it does what you need
