### ISSUE TITLE
Make documentation

### ISSUE THREAD

**Issue by chemphys** [i-pi/i-pi#6]
Hi! I was trying to compile the documentation in i-pi/doc, but even if I use the makefile or type just 'python create_man.py', it gives me an error. 

python create_man.py
Traceback (most recent call last):
  File "create_man.py", line 33, in <module>
    from help import help, objects
  File "/home/mriera/codes/i-pi/doc/help.py", line 45, in <module>
    from ipi.inputs import *
  File "../ipi/inputs/barostats.py", line 25, in <module>
    import ipi.engine.thermostats
  File "../ipi/engine/thermostats.py", line 47, in <module>
    from ipi.utils.depend   import *
  File "../ipi/utils/depend.py", line 61, in <module>
    from ipi.utils.messages import verbosity, warning
  File "../ipi/utils/messages.py", line 105
    print """usage:  %s input """%sys.argv[0]
                                ^
SyntaxError: Missing parentheses in call to 'print'
make: **\* [aux] Error 1

I cannot see why this is not working. If I comment the printing statement that is failing, I just get similar errors. I use anaconda3 python with python 3.4.

Thanks!

**Comment by chemphys** [comment]
I realized that there is a branch called docfix. Maybe is not merged?

**Comment by OndrejMarsalek** [comment]
Hi Marc, you need to use Python 2 to run i-PI. A transition to Python 3 will surely happen at some point in the future, but for compatibility reasons, we stick with Python 2 for now.

**Comment by ceriottm** [comment]
Hi Marc, Ondrej is right with Py2 it should work without problems. If you are interested and brave there is also a much more updated dev version we are working on, in a private repo. Mail me privately and I'll give you access.

**Comment by chemphys** [comment]
Oh, Thanks! I don't know enough yet though. I will play around with this version with python 2.7. I am trying to couple a energy code to the md simulations that i-pi has. Let's see if I can do it!

See you around!


.   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
Marc Riera-Riambau
Graduate Student @ Paesani Group
University of California, San Diego
Phone: +1 858 750 9866
Mail: mrierari@ucsd.edu
________________________________________
De: Michele Ceriotti [notifications@github.com]
Enviado: jueves, 28 de enero de 2016 23:38
Para: i-pi/i-pi
CC: Marc Riera Riambau
Asunto: Re: [i-pi] Make documentation (#6)

Hi Marc, Ondrej is right with Py2 it should work without problems. If you are interested and brave there is also a much more updated dev version we are working on, in a private repo. Mail me privately and I'll give you access.

�

**Comment by chemphys** [comment]
Hey, following up in the issue. Is the python3 version available? Or still needs python 2?

**Comment by ceriottm** [comment]
This is still on python2. We'll transition to Py3 in v 3.0
