### ISSUE TITLE
Running on one machine with multiple processors.

### ISSUE THREAD

**Issue by jcminerlanl** [i-pi/i-pi#9]
Hello,

I am running through your tutorials and plan to use this code for a number of applications in the near future. I find my computational speed significantly hindered on my main device (HP Z440: 12 Intel Xeon E5-1650 v3 CPUs).
I am running examples based on the tests you have on GitHub, but the program only runs on a single processor when it has 12 available.
Is there a way to parallelize the job over all the available processors?

**Comment by jcminerlanl** [comment]
And another question:
For patching to cp2k version 4.1_1, what needs to be changed in earlier patch files?
The cp2k on my machine is at the following address:
/usr/local/Cellar/cp2k/4.1_1

My i-pi is at:
/Users/jcminer/i-pi/

**Comment by ceriottm** [comment]
You don't need to patch recent versions of CP2K, the i-PI interface is part
of the standard distribution. Generally speaking -- particularly if you
plan to run CP2K -- there is no reason to parallelize i-PI: the bottleneck
is going to be the CP2K client. From that PoV, you can either run CP2K in
parallel, or (if you're performing path integral simulations) run multiple
copies of CP2k: i-PI will distribute the load among them.
