### ISSUE TITLE
Instanton_interpolation.py tools makes use of option "instanton=True" in nm_rescale which doesn't exist.

### ISSUE THREAD

**Issue by heindelj** [i-pi/i-pi#91]
I know these tools are provided mostly as a convenience, but I thought I'd point this out anyways.
In the Instanton_interpolation.py script, there is a line,

`rpc = nm_rescale(nbeads, nbeadsNew, instanton=True)`

I assume this instanton option has been removed, and the tool not updated. It looks to me like the line above this one, which is commented out, does what is desired, which is to enable "open path" mode of nm_rescale by having any argument there.

`rpc = nm_rescale(nbeads, nbeadsNew, np.asarray(range(1)))  # We use open path RPC`

When I uncomment that line and comment the other one, the code runs successfully and calculates a hessian. I don't submit this as a pull request as I'm not 100% sure if uncommenting that line gives the exact functionality you want, as there are some other lines which talk about using open-paths which are still commented out, but it seems like nm_rescale has been modified since this script was written without the script changing.

Obviously, not a very urgent issue.

**Comment by litman90** [comment]
Hi,
I am about to create a PR with some improvements and this bugfix.
Thanks for pointing it out.

I can't say if what you did is correct because it also depends on other lines in the scripts.

**Comment by litman90** [comment]
It has been fixed in PR #121.

**Comment by litman90** [comment]
The PR has been merged so this issue has been solved.
