### ISSUE TITLE
Instanton_postproc.py needs to access hessian, energies, ... differently for "TS" mode.

### ISSUE THREAD

**Issue by heindelj** [i-pi/i-pi#92]
The lines:
`h = simulation.syslist[0].motion.hessian.copy()`
`pots = simulation.syslist[0].motion.old_u`
`V0 = simulation.syslist[0].motion.energy_shift`

need to be changed to:
`h = simulation.syslist[0].motion.optarrays["hessian"].copy()`
`pots = simulation.syslist[0].motion.optarrays["old_u"]`
`V0 = simulation.syslist[0].motion.optarrays["energy_shift"]`

**Comment by litman90** [comment]
Hi,
I am about to create a PR with some improvements and this bugfix.
Thanks for pointing it out.

**Comment by litman90** [comment]
Just for the records, what you suggest is correct.

**Comment by litman90** [comment]
It has been fixed in PR #121.

**Comment by litman90** [comment]
The PR has been merged so this issue has been solved.
